# Module 2 - Data Quality Enhancement

## Input:
university_raw_data.csv

## Output:
university_cleaned.csv

## Objective:
Improve dataset quality through rule-based recovery, interpolation, statistical imputation, and machine learning.

This notebook improves the quality of the cleaned higher education dataset using statistical and machine learning based imputation techniques.

Goals

- Reduce missing values below 2%
- Preserve historical consistency
- Improve data completeness
- Generate a Tableau / Power BI ready dataset

Dataset Timeline

2017–2026

In [1]:
from pathlib import Path

import numpy as np
import pandas as pd

from sklearn.impute import KNNImputer
from sklearn.ensemble import RandomForestRegressor

pd.set_option("display.max_columns", None)

In [2]:
# ==========================================
# Paths
# ==========================================

SCRIPT_DIR = Path.cwd().parent.parent

INPUT_PATH = (
    SCRIPT_DIR /
    "datasets" /
    "final" /
    "Module_1_Deliverables" /
    "university_raw_data.csv"
)

OUTPUT_PATH = (
    SCRIPT_DIR /
    "datasets" /
    "final" /
    "Module_2_Deliverables"
)

OUTPUT_FILE = (
    OUTPUT_PATH /
    "university_cleaned.csv"
)

In [3]:
df = pd.read_csv(
    INPUT_PATH,
    low_memory=False
)

print(df.shape)

df.head()

(23263, 36)

,University,Country,Country Code,City,Region,University Type,University Age Band,Academic Reputation Score,Employer Reputation Score,Faculty Student Score,Citations per Faculty Score,International Faculty Score,International Students Score,International Research Network Score,Employment Outcomes Score,Sustainability Score,Faculty Count,Research Output,Year,Student Population,Teaching,Research Environment,Research Quality,Industry Impact,International Outlook,Publications,Citation Count,h-index,Research Productivity Index,Subject Area,Female Student Percentage,Male Student Percentage,Overall Score,Students to Staff Ratio,International Students,Continent
0,Don State Technical University,Russia,RU,Rostov-on-Don,Europe,Public,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"1,860",High,2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Life Sciences & Medicine,NaN,NaN,NaN,14.0,"2,627",Europe
1,Don State Technical University,Russia,RU,Rostov-on-Don,Europe,Public,4.0,3.7,3.6,12.7,1.4,1.6,15.7,12.2,3.4,NaN,NaN,NaN,2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Life Sciences & Medicine,NaN,NaN,NaN,NaN,NaN,Europe
2,Don State Technical University,Russia,RU,Rostov-on-Don,Europe,Public,4.0,4.2,3.1,13.3,1.4,1.6,14.8,1.0,7.2,1.3,NaN,NaN,2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Life Sciences & Medicine,NaN,NaN,NaN,NaN,NaN,Europe
3,Don State Technical University,Russia,RU,Rostov-on-Don,Europe,Public,4.0,3.5,3.5,12.8,1.4,1.6,14.9,11.4,1.9,1.0,NaN,NaN,2025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Life Sciences & Medicine,NaN,NaN,NaN,NaN,NaN,Europe
4,ULACIT - Universidad Latinoamericana de Cienc...,Costa Rica,CR,San José,Latin America,Private,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,218,Low,2017,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Arts & Humanities,NaN,NaN,NaN,14.0,NaN,North America

In [4]:
print("="*70)
print("INITIAL DATA QUALITY")
print("="*70)

print(f"Rows    : {len(df):,}")
print(f"Columns : {len(df.columns)}")

missing_total = df.isna().sum().sum()

total_cells = df.shape[0] * df.shape[1]

missing_percent = (
    missing_total /
    total_cells *
    100
)

print(f"\nTotal Missing Values : {missing_total:,}")

print(f"Dataset Completeness : {100-missing_percent:.2f}%")

======================================================================
INITIAL DATA QUALITY
======================================================================
Rows    : 23,263
Columns : 36

Total Missing Values : 286,961
Dataset Completeness : 65.73%

In [5]:
initial_missing = (
    df.isna()
      .sum()
      .sort_values(ascending=False)
      .to_frame("Missing Values")
)

initial_missing["Missing %"] = (
    initial_missing["Missing Values"] /
    len(df) *
    100
).round(2)

display(initial_missing)

                                      Missing Values  Missing %
Sustainability Score                           18903      81.26
International Faculty Score                    17748      76.29
International Students Score                   17569      75.52
International Research Network Score           17392      74.76
Employment Outcomes Score                      17375      74.69
Citations per Faculty Score                    17366      74.65
Faculty Student Score                          17363      74.64
Employer Reputation Score                      17339      74.53
Faculty Count                                  16858      72.47
Research Output                                16782      72.14
Academic Reputation Score                      14517      62.40
City                                           11387      48.95
University Age Band                            10599      45.56
International Outlook                           7350      31.60
Research Environment                            7350      31.60
Industry Impact                                 7350      31.60
Student Population                              7350      31.60
Research Quality                                7350      31.60
Teaching                                        7350      31.60
Overall Score                                   6405      27.53
International Students                          3732      16.04
Students to Staff Ratio                         3655      15.71
Research Productivity Index                     2911      12.51
Male Student Percentage                         2911      12.51
Female Student Percentage                       2911      12.51
h-index                                         2911      12.51
Publications                                    2911      12.51
Citation Count                                  2911      12.51
University Type                                  395       1.70
Subject Area                                       6       0.03
Country Code                                       4       0.02
Country                                            0       0.00
University                                         0       0.00
Region                                             0       0.00
Year                                               0       0.00
Continent                                          0       0.00

In [6]:
important_columns = [

    "Academic Reputation Score",
    "Employer Reputation Score",
    "Faculty Student Score",
    "Citations per Faculty Score",
    "International Faculty Score",
    "International Students Score",
    "International Research Network Score",
    "Employment Outcomes Score",
    "Sustainability Score",

    "Teaching",
    "Research Environment",
    "Research Quality",
    "Industry Impact",
    "International Outlook"
]

availability = (
    df.groupby("Year")[important_columns]
      .apply(lambda x: x.notna().sum())
)

display(availability)

,Academic Reputation Score,Employer Reputation Score,Faculty Student Score,Citations per Faculty Score,International Faculty Score,International Students Score,International Research Network Score,Employment Outcomes Score,Sustainability Score,Teaching,Research Environment,Research Quality,Industry Impact,International Outlook
Year,,,,,,,,,,,,,,
2017,404,0,0,0,0,0,0,0,0,981,981,981,981,981
2018,403,0,0,0,0,0,0,0,0,1103,1103,1103,1103,1103
2019,505,0,0,0,0,0,0,0,0,1258,1258,1258,1258,1258
2020,501,0,0,0,0,0,0,0,0,1397,1397,1397,1397,1397
2021,506,0,0,0,0,0,0,0,0,1526,1526,1526,1526,1526
2022,501,0,0,0,0,0,0,0,0,1662,1662,1662,1662,1662
2023,1423,1422,1421,1418,1325,1366,1410,1411,0,1799,1799,1799,1799,1799
2024,1498,1497,1474,1474,1372,1418,1494,1474,1398,1904,1904,1904,1904,1904
2025,1504,1504,1504,1504,1404,1446,1503,1504,1485,2092,2092,2092,2092,2092
2026,1501,1501,1501,1501,1414,1464,1464,1499,1477,2191,2191,2191,2191,2191

In [7]:
# ==========================================
# Column Categories
# ==========================================

static_columns = [

    "Country",
    "Country Code",
    "Region",
    "Continent",
    "City",
    "University Type",
    "Subject Area"

]

time_series_columns = [

    "Student Population",
    "Faculty Count",
    "Students to Staff Ratio",
    "International Students",
    "Female Student Percentage",
    "Male Student Percentage"

]

research_columns = [

    "Publications",
    "Citation Count",
    "h-index",
    "Research Productivity Index"

]

print("Static :", len(static_columns))
print("Time :", len(time_series_columns))
print("Research :", len(research_columns))

Static : 7
Time : 6
Research : 4

In [8]:
# ==========================================
# Static Value Recovery
# ==========================================

for column in static_columns:

    df[column] = (

        df.groupby("University")[column]

          .transform(

              lambda x: x.ffill().bfill()

          )

    )

print("Static recovery completed.")

Static recovery completed.

In [9]:
before = initial_missing.copy()

after = (

    df[static_columns]

      .isna()

      .sum()

      .to_frame("Remaining Missing")

)

display(after)

                 Remaining Missing
Country                          0
Country Code                     4
Region                           0
Continent                        0
City                         11387
University Type                395
Subject Area                     6

In [10]:
# ==========================================
# Country-wise Categorical Recovery
# ==========================================

categorical_columns = [
    "University Type",
    "Subject Area"
]

for column in categorical_columns:

    mode_lookup = (
        df.groupby("Country")[column]
          .agg(
              lambda x: x.mode().iloc[0]
              if not x.mode().empty
              else np.nan
          )
    )

    df[column] = (
        df[column]
          .fillna(df["Country"].map(mode_lookup))
    )

print("Country-wise categorical recovery completed.")

Country-wise categorical recovery completed.

In [11]:
# ==========================================
# Recovery Report
# ==========================================

report = (
    df[
        [
            "Country",
            "Country Code",
            "Region",
            "Continent",
            "City",
            "University Type",
            "Subject Area"
        ]
    ]
    .isna()
    .sum()
    .to_frame("Remaining Missing")
)

display(report)

                 Remaining Missing
Country                          0
Country Code                     4
Region                           0
Continent                        0
City                         11387
University Type                395
Subject Area                     6

In [12]:
# ==========================================
# Sort Dataset
# ==========================================

df = (
    df
    .sort_values(
        ["University", "Year"]
    )
    .reset_index(drop=True)
)

In [13]:
# ==========================================
# University-wise Interpolation
# ==========================================

time_columns = [

    "Student Population",
    "Faculty Count",
    "Students to Staff Ratio",
    "International Students",
    "Female Student Percentage",
    "Male Student Percentage"

]

for column in time_columns:

    df[column] = (
        df.groupby("University")[column]
          .transform(
              lambda x: (
                  pd.to_numeric(
                      x.astype(str)
                       .str.replace(",", "", regex=False)
                       .str.replace("%", "", regex=False)
                       .str.strip(),
                      errors="coerce"
                  ).interpolate(method="linear", limit_direction="both")
              )
          )
    )

print("Interpolation completed.")

Interpolation completed.

In [14]:
# ==========================================
# Time-Series Recovery Report
# ==========================================

report = (

    df[time_columns]

      .isna()

      .sum()

      .to_frame("Remaining Missing")

)

display(report)

                           Remaining Missing
Student Population                      5956
Faculty Count                          11095
Students to Staff Ratio                  895
International Students                  1017
Female Student Percentage               2911
Male Student Percentage                 2911

In [15]:
# ==========================================
# Missing Values by Year
# ==========================================

missing_by_year = (
    df.groupby("Year")
      .apply(lambda x: x.isna().sum().sum())
      .to_frame("Missing Values")
)

missing_by_year["Completeness (%)"] = (
    (
        1
        - missing_by_year["Missing Values"]
        / (df.shape[1] * df.groupby("Year").size())
    )
    * 100
).round(2)

display(missing_by_year)

      Missing Values  Completeness (%)
Year
2017           20500             62.73
2018           22514             62.66
2019           24714             62.85
2020           26808             62.86
2021           29736             62.62
2022           32747             62.43
2023           27252             71.43
2024           27789             72.47
2025           30083             72.01
2026           32186             71.49

In [16]:
# ==========================================
# Top Missing Columns
# ==========================================

missing = (
    df.isna()
      .sum()
      .sort_values(ascending=False)
      .to_frame("Missing")
)

missing["Missing %"] = (
    missing["Missing"] / len(df) * 100
).round(2)

display(missing.head(20))

                                      Missing  Missing %
Sustainability Score                    18903      81.26
International Faculty Score             17748      76.29
International Students Score            17569      75.52
International Research Network Score    17392      74.76
Employment Outcomes Score               17375      74.69
Citations per Faculty Score             17366      74.65
Faculty Student Score                   17363      74.64
Employer Reputation Score               17339      74.53
Research Output                         16782      72.14
Academic Reputation Score               14517      62.40
City                                    11387      48.95
Faculty Count                           11095      47.69
University Age Band                     10599      45.56
International Outlook                    7350      31.60
Research Environment                     7350      31.60
Research Quality                         7350      31.60
Industry Impact                          7350      31.60
Teaching                                 7350      31.60
Overall Score                            6405      27.53
Student Population                       5956      25.60

In [17]:
# ==========================================
# QS Metrics Missing Values
# ==========================================

qs_metrics = [

    "Academic Reputation Score",
    "Employer Reputation Score",
    "Faculty Student Score",
    "Citations per Faculty Score",
    "International Faculty Score",
    "International Students Score",
    "International Research Network Score",
    "Employment Outcomes Score",
    "Sustainability Score"

]

qs_missing = (

    df[qs_metrics]

      .isna()

      .sum()

      .to_frame("Missing")

)

qs_missing["Missing %"] = (

    qs_missing["Missing"]

    / len(df)

    * 100

).round(2)

display(qs_missing)

                                      Missing  Missing %
Academic Reputation Score               14517      62.40
Employer Reputation Score               17339      74.53
Faculty Student Score                   17363      74.64
Citations per Faculty Score             17366      74.65
International Faculty Score             17748      76.29
International Students Score            17569      75.52
International Research Network Score    17392      74.76
Employment Outcomes Score               17375      74.69
Sustainability Score                    18903      81.26

In [18]:
# ==========================================
# Research Metrics
# ==========================================

research_metrics = [

    "Publications",
    "Citation Count",
    "h-index",
    "Research Productivity Index"

]

display(

    df[research_metrics]

      .isna()

      .sum()

)

Publications                   2911
Citation Count                 2911
h-index                        2911
Research Productivity Index    2911
dtype: int64

In [19]:
# ==========================================
# Recovery Candidates
# ==========================================

candidate_columns = [

    "Student Population",
    "Faculty Count",
    "Students to Staff Ratio",
    "International Students",
    "Female Student Percentage",
    "Male Student Percentage",
    "University Type",
    "Subject Area",
    "City"

]

candidate_missing = (

    df[candidate_columns]

      .isna()

      .sum()

      .to_frame("Missing")

)

display(candidate_missing)

                           Missing
Student Population            5956
Faculty Count                11095
Students to Staff Ratio        895
International Students        1017
Female Student Percentage     2911
Male Student Percentage       2911
University Type                395
Subject Area                     6
City                         11387

In [20]:
# ==========================================
# Country-wise Numeric Imputation
# ==========================================

numeric_columns = [
    "Student Population",
    "Faculty Count",
    "Students to Staff Ratio",
    "International Students",
    "Female Student Percentage",
    "Male Student Percentage"
]

for column in numeric_columns:

    country_median = (
        df.groupby("Country")[column]
          .transform("median")
    )

    df[column] = df[column].fillna(country_median)

print("Country-wise numeric imputation completed.")

Country-wise numeric imputation completed.

In [21]:
# ==========================================
# Global Median Fallback
# ==========================================

for column in numeric_columns:
    df[column] = df[column].fillna(df[column].median())

print("Global fallback completed.")

Global fallback completed.

In [22]:
remaining = (
    df[numeric_columns]
      .isna()
      .sum()
      .to_frame("Remaining Missing")
)

display(remaining)

                           Remaining Missing
Student Population                         0
Faculty Count                              0
Students to Staff Ratio                    0
International Students                     0
Female Student Percentage                  0
Male Student Percentage                    0

In [23]:
# ==========================================
# Enable Experimental Iterative Imputer
# ==========================================

from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

In [24]:
# ==========================================
# Features for Imputation
# ==========================================

imputation_columns = [

    "Overall Score",

    "Teaching",
    "Research Environment",
    "Research Quality",
    "Industry Impact",
    "International Outlook",

    "Publications",
    "Citation Count",
    "h-index",
    "Research Productivity Index",

    "Academic Reputation Score",
    "Employer Reputation Score",
    "Faculty Student Score",
    "Citations per Faculty Score",
    "International Faculty Score",
    "International Students Score",
    "International Research Network Score",
    "Employment Outcomes Score",
    "Sustainability Score"

]

In [25]:
# ==========================================
# Year-wise Iterative Imputation
# ==========================================

for year in sorted(df["Year"].unique()):

    year_mask = df["Year"] == year

    year_data = df.loc[
        year_mask,
        imputation_columns
    ]

    if year_data.isna().sum().sum() == 0:
        continue

    imputer = IterativeImputer(
        random_state=42,
        max_iter=20
    )

    # ensure numeric inputs and preserve index/columns for assignment
    year_numeric = year_data.apply(
        lambda col: pd.to_numeric(
            col.astype(str)
               .str.replace(",", "", regex=False)
               .str.replace("%", "", regex=False)
               .str.strip(),
            errors="coerce"
        )
    )

    imputed = imputer.fit_transform(year_numeric)

    # Get columns that had data (non-all-NaN)
    valid_cols = year_numeric.columns[year_numeric.notna().any()].tolist()
    
    # Create DataFrame with imputed values using only valid columns
    imputed_df = pd.DataFrame(
        imputed,
        index=year_data.index,
        columns=valid_cols
    )
    
    # Assign back to dataframe
    # Align and assign imputed DataFrame directly to preserve index/column alignment
    # ensure target columns in the main df are numeric (so float assignment is allowed)
    df[valid_cols] = df[valid_cols].apply(
        lambda col: pd.to_numeric(
            col.astype(str)
               .str.replace(",", "", regex=False)
               .str.replace("%", "", regex=False)
               .str.strip(),
            errors="coerce"
        )
    )

    # assign imputed values aligning by index and columns
    df.loc[year_data.index, valid_cols] = imputed_df.astype(float).values

print("Year-wise MICE imputation completed.")

C:\Users\shashank\AppData\Roaming\Python\Python312\site-packages\sklearn\impute\_base.py:647: UserWarning: Skipping features without any observed values: [11 12 13 14 15 16 17 18]. At least one non-missing value is needed for imputation with strategy='mean'.
  warnings.warn(
C:\Users\shashank\AppData\Roaming\Python\Python312\site-packages\sklearn\impute\_iterative.py:867: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(
C:\Users\shashank\AppData\Roaming\Python\Python312\site-packages\sklearn\impute\_base.py:647: UserWarning: Skipping features without any observed values: [11 12 13 14 15 16 17 18]. At least one non-missing value is needed for imputation with strategy='mean'.
  warnings.warn(
C:\Users\shashank\AppData\Roaming\Python\Python312\site-packages\sklearn\impute\_iterative.py:867: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(
C:\Users\shashank\AppData\Roaming\Python\Python312\site-packages\sklearn\impute\_base.py:647: UserWarning: Skipping features without any observed values: [11 12 13 14 15 16 17 18]. At least one non-missing value is needed for imputation with strategy='mean'.
  warnings.warn(
C:\Users\shashank\AppData\Roaming\Python\Python312\site-packages\sklearn\impute\_base.py:647: UserWarning: Skipping features without any observed values: [11 12 13 14 15 16 17 18]. At least one non-missing value is needed for imputation with strategy='mean'.
  warnings.warn(
C:\Users\shashank\AppData\Roaming\Python\Python312\site-packages\sklearn\impute\_iterative.py:867: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(
C:\Users\shashank\AppData\Roaming\Python\Python312\site-packages\sklearn\impute\_base.py:647: UserWarning: Skipping features without any observed values: [11 12 13 14 15 16 17 18]. At least one non-missing value is needed for imputation with strategy='mean'.
  warnings.warn(
C:\Users\shashank\AppData\Roaming\Python\Python312\site-packages\sklearn\impute\_iterative.py:867: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(
C:\Users\shashank\AppData\Roaming\Python\Python312\site-packages\sklearn\impute\_base.py:647: UserWarning: Skipping features without any observed values: [11 12 13 14 15 16 17 18]. At least one non-missing value is needed for imputation with strategy='mean'.
  warnings.warn(
C:\Users\shashank\AppData\Roaming\Python\Python312\site-packages\sklearn\impute\_iterative.py:867: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(
C:\Users\shashank\AppData\Roaming\Python\Python312\site-packages\sklearn\impute\_base.py:647: UserWarning: Skipping features without any observed values: [18]. At least one non-missing value is needed for imputation with strategy='mean'.
  warnings.warn(
C:\Users\shashank\AppData\Roaming\Python\Python312\site-packages\sklearn\impute\_iterative.py:867: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(
C:\Users\shashank\AppData\Roaming\Python\Python312\site-packages\sklearn\impute\_iterative.py:867: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(
C:\Users\shashank\AppData\Roaming\Python\Python312\site-packages\sklearn\impute\_iterative.py:867: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(
C:\Users\shashank\AppData\Roaming\Python\Python312\site-packages\sklearn\impute\_iterative.py:867: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn(

Year-wise MICE imputation completed.

In [26]:
# ==========================================
# Remaining Missing Values
# ==========================================

remaining = (
    df[imputation_columns]
      .isna()
      .sum()
      .sort_values(ascending=False)
      .to_frame("Remaining Missing")
)

display(remaining)

                                      Remaining Missing
Sustainability Score                              14337
Employment Outcomes Score                         11687
International Students Score                      11687
Faculty Student Score                             11687
Citations per Faculty Score                       11687
Employer Reputation Score                         11687
International Research Network Score              11687
International Faculty Score                       11687
Research Environment                                  0
Overall Score                                         0
Teaching                                              0
Academic Reputation Score                             0
Research Productivity Index                           0
h-index                                               0
Citation Count                                        0
Publications                                          0
International Outlook                                 0
Industry Impact                                       0
Research Quality                                      0

In [27]:
# ==========================================
# Random Forest Imputation
# ==========================================

from sklearn.ensemble import RandomForestRegressor

In [28]:
# ==========================================
# Features Used For Prediction
# ==========================================

feature_columns = [

    "Overall Score",

    "Teaching",
    "Research Environment",
    "Research Quality",
    "Industry Impact",
    "International Outlook",

    "Publications",
    "Citation Count",
    "h-index",
    "Research Productivity Index",

    "Student Population",
    "Faculty Count",
    "Students to Staff Ratio",
    "International Students"

]

In [29]:
# ==========================================
# Target Columns
# ==========================================

target_columns = [

    "Academic Reputation Score",
    "Employer Reputation Score",
    "Faculty Student Score",
    "Citations per Faculty Score",
    "International Faculty Score",
    "International Students Score",
    "International Research Network Score",
    "Employment Outcomes Score",
    "Sustainability Score"

]

In [30]:
# ==========================================
# Random Forest Imputation
# ==========================================

for target in target_columns:

    train = df[df[target].notna()].copy()

    predict = df[df[target].isna()].copy()

    if len(predict) == 0:
        continue

    train = train.dropna(subset=feature_columns)

    predict = predict.dropna(subset=feature_columns)

    if len(train) < 100:
        continue

    model = RandomForestRegressor(

        n_estimators=300,

        random_state=42,

        n_jobs=-1

    )

    model.fit(

        train[feature_columns],

        train[target]

    )

    predicted = model.predict(

        predict[feature_columns]

    )

    df.loc[
        predict.index,
        target
    ] = predicted

    print(f"{target:<45} Filled : {len(predicted)}")

Employer Reputation Score                     Filled : 11687
Faculty Student Score                         Filled : 11687
Citations per Faculty Score                   Filled : 11687
International Faculty Score                   Filled : 11687
International Students Score                  Filled : 11687
International Research Network Score          Filled : 11687
Employment Outcomes Score                     Filled : 11687
Sustainability Score                          Filled : 14337

In [31]:
# ==========================================
# Remaining Missing
# ==========================================

remaining = (

    df[target_columns]

      .isna()

      .sum()

      .sort_values()

      .to_frame("Remaining Missing")

)

display(remaining)

                                      Remaining Missing
Academic Reputation Score                             0
Employer Reputation Score                             0
Faculty Student Score                                 0
Citations per Faculty Score                           0
International Faculty Score                           0
International Students Score                          0
International Research Network Score                  0
Employment Outcomes Score                             0
Sustainability Score                                  0

In [32]:
# ==========================================
# Overall Dataset Quality
# ==========================================

missing_total = df.isna().sum().sum()

total_cells = df.shape[0] * df.shape[1]

completeness = (
    100 -
    (
        missing_total /
        total_cells
    ) * 100
)

print("="*70)

print(f"Missing Values : {missing_total:,}")

print(f"Completeness : {completeness:.2f}%")

print("="*70)

======================================================================
Missing Values : 39,173
Completeness : 95.32%
======================================================================

In [33]:
# ==========================================
# University-wise Metadata Recovery
# ==========================================

metadata_columns = [

    "City",
    "University Type",
    "Research Output",
    "University Age Band",
    "Subject Area"

]

for column in metadata_columns:

    if column not in df.columns:
        continue

    df[column] = (

        df.groupby("University")[column]

          .transform(

              lambda x: x.ffill().bfill()

          )

    )

print("Metadata recovery completed.")

Metadata recovery completed.

In [34]:
# ==========================================
# Country-wise Metadata Recovery
# ==========================================

for column in metadata_columns:

    if column not in df.columns:
        continue

    mode_lookup = (

        df.groupby("Country")[column]

          .agg(

              lambda x:

              x.mode().iloc[0]

              if not x.mode().empty

              else np.nan

          )

    )

    df[column] = (

        df[column]

          .fillna(

              df["Country"].map(mode_lookup)

          )

    )

print("Country metadata recovery completed.")

Country metadata recovery completed.

In [35]:
# ==========================================
# Remaining Metadata Missing Values
# ==========================================

existing_metadata_columns = [
    column for column in metadata_columns
    if column in df.columns
]

if existing_metadata_columns:
    display(
        df[existing_metadata_columns]
          .isna()
          .sum()
          .to_frame("Remaining Missing")
    )
else:
    print("No metadata columns found in the dataframe.")

                     Remaining Missing
City                               454
University Type                    395
Research Output                    395
University Age Band                250
Subject Area                         6

In [36]:
# ==========================================
# Data Quality Audit
# ==========================================

numeric_cols = df.select_dtypes(include="number").columns

print("=" * 70)
print("DATA QUALITY AUDIT")
print("=" * 70)

for col in numeric_cols:
    print(f"\n{col}")
    print(f"  Min : {df[col].min()}")
    print(f"  Max : {df[col].max()}")
    print(f"  Missing : {df[col].isna().sum()}")

======================================================================
DATA QUALITY AUDIT
======================================================================

University Age Band
  Min : 1.0
  Max : 5.0
  Missing : 250

Academic Reputation Score
  Min : -271.5755348601168
  Max : 124.0869250611195
  Missing : 0

Employer Reputation Score
  Min : -13.1845438257561
  Max : 108.883895965168
  Missing : 0

Faculty Student Score
  Min : -85.6691051470306
  Max : 127.96362907987617
  Missing : 0

Citations per Faculty Score
  Min : -71.97845741350392
  Max : 135.03992455903997
  Missing : 0

International Faculty Score
  Min : -116.1914786720688
  Max : 111.9075316988426
  Missing : 0

International Students Score
  Min : -87.67119822387117
  Max : 100.0
  Missing : 0

International Research Network Score
  Min : -33.32612550871467
  Max : 130.24027333664682
  Missing : 0

Employment Outcomes Score
  Min : -3.0851495729478207
  Max : 126.94126982129394
  Missing : 0

Sustainability Score
  Min : -18.578398234580977
  Max : 115.33615173323972
  Missing : 0

Faculty Count
  Min : 1.0
  Max : 20311.0
  Missing : 0

Year
  Min : 2017
  Max : 2026
  Missing : 0

Student Population
  Min : 25.0
  Max : 1824383.0
  Missing : 0

Teaching
  Min : 5.979335892368981
  Max : 99.2
  Missing : 0

Research Environment
  Min : -20.232326202766444
  Max : 100.0
  Missing : 0

Research Quality
  Min : -9.316141518563384
  Max : 115.88214967299615
  Missing : 0

Industry Impact
  Min : -29.673812000434083
  Max : 125.40943318250049
  Missing : 0

International Outlook
  Min : 7.9
  Max : 106.49580211706498
  Missing : 0

Publications
  Min : -16551.266442887943
  Max : 426694.0
  Missing : 0

Citation Count
  Min : -88728.90222057194
  Max : 2857811.0
  Missing : 0

h-index
  Min : -82.68497490325566
  Max : 1699.0
  Missing : 0

Research Productivity Index
  Min : 0.35
  Max : 10.23
  Missing : 0

Female Student Percentage
  Min : 20.0
  Max : 100.0
  Missing : 0

Male Student Percentage
  Min : 0.0
  Max : 80.0
  Missing : 0

Overall Score
  Min : 4.401845607014032
  Max : 100.0
  Missing : 0

Students to Staff Ratio
  Min : 0.3
  Max : 865.8
  Missing : 0

International Students
  Min : 0.0
  Max : 31049.0
  Missing : 0

In [37]:
# ==========================================
# Invalid Range Report
# ==========================================

score_columns = [
    "Academic Reputation Score",
    "Employer Reputation Score",
    "Faculty Student Score",
    "Citations per Faculty Score",
    "International Faculty Score",
    "International Students Score",
    "International Research Network Score",
    "Employment Outcomes Score",
    "Sustainability Score",
    "Teaching",
    "Research Environment",
    "Research Quality",
    "Industry Impact",
    "International Outlook"
]

for col in score_columns:
    if col in df.columns:
        invalid = df[(df[col] < 0) | (df[col] > 100)]

        if len(invalid) > 0:
            print(f"\n{'='*70}")
            print(f"{col}")
            print(f"Invalid values: {len(invalid)}")
            print(invalid[["University", col]].head(10))

======================================================================
Academic Reputation Score
Invalid values: 211
                                         University  Academic Reputation Score
89                Abdul Wali Khan University Mardan                  -1.359311
144                             Acıbadem University                  -1.007889
199                        Aichi Medical University                  -0.310984
222                                  Air University                  -2.437188
223                                  Air University                  -1.965335
480  American International University – Bangladesh                  -0.980727
520                   American University of Beirut                  -1.203982
604                    An-Najah National University                 -14.002040
606                    An-Najah National University                  -2.205081
611                              Anadolu University                -271.575535

======================================================================
Employer Reputation Score
Invalid values: 230
                                         University  Employer Reputation Score
89                Abdul Wali Khan University Mardan                  -3.929331
90                Abdul Wali Khan University Mardan                  -2.813256
222                                  Air University                  -4.399730
223                                  Air University                  -4.935539
318                           Al al-Bayt University                  -3.084399
480  American International University – Bangladesh                  -3.960024
584              Amity University Rajasthan, Jaipur                  -1.269252
604                    An-Najah National University                 -11.198776
606                    An-Najah National University                  -0.921767
719             Arak University of Medical Sciences                 -11.823771

======================================================================
Faculty Student Score
Invalid values: 348
                                 University  Faculty Student Score
86            Abdelmalek Essaâdi University              -9.825603
159      Adam Mickiewicz University, Poznań             -24.560841
318                   Al al-Bayt University              -2.382533
319                   Al al-Bayt University             -17.480306
325                     Al-Azhar University              -7.778745
326                     Al-Azhar University             -12.121712
327                     Al-Azhar University             -19.006650
328                     Al-Azhar University             -24.392903
332                     Al-Azhar University             -36.122079
353  Al-Furat Al-Awsat Technical University              -7.711532

======================================================================
Citations per Faculty Score
Invalid values: 171
                 University  Citations per Faculty Score
144     Acıbadem University                    -3.675177
209    Ain Shams University                    -2.902792
210    Ain Shams University                   -39.520777
328     Al-Azhar University                    -8.809120
392   Alexandria University                   -25.861671
393   Alexandria University                   -29.619588
456  Altai State University                    -2.293517
611      Anadolu University                   -36.157656
612      Anadolu University                   -27.585511
613      Anadolu University                   -27.443435

======================================================================
International Faculty Score
Invalid values: 2560
                        University  International Faculty Score
26        AGH University of Krakow                    -2.444650
29        AGH University of Krakow                    -1.264985
30        AGH University of Krakow                    -0.697879
43                 AIIMS Rishikesh                    -9.084348
83   Abdelmalek Essaâdi University                    -7.392734
84   Abdelmalek Essaâdi University                    -5.997715
86   Abdelmalek Essaâdi University                    -4.394771
132   Acharya Nagarjuna University                   -13.202743
133   Acharya Nagarjuna University                    -8.777374
134   Acharya Nagarjuna University                    -4.071744

======================================================================
International Students Score
Invalid values: 2457
                        University  International Students Score
25        AGH University of Krakow                     -2.067138
26        AGH University of Krakow                     -4.769406
27        AGH University of Krakow                     -0.448712
29        AGH University of Krakow                     -0.691501
83   Abdelmalek Essaâdi University                     -0.737421
84   Abdelmalek Essaâdi University                     -5.055650
85   Abdelmalek Essaâdi University                     -0.340879
132   Acharya Nagarjuna University                     -5.507139
133   Acharya Nagarjuna University                     -1.724351
141            Acıbadem University                     -6.246059

======================================================================
International Research Network Score
Invalid values: 299
                                             University  \
138                        Acharya Nagarjuna University
145                                 Acıbadem University
200                            Aichi Medical University
292                                    Akita University
358                               Al-Nahrain University
458                              Altai State University
679                                Annamalai University
931                      Australian National University
993   B. S. Abdur Rahman Crescent Institute of Scien...
1364        Belgorod State National Research University

      International Research Network Score
138                              -1.388507
145                              -6.105699
200                             -13.207234
292                              -6.414576
358                              -8.969352
458                              -4.720995
679                              -3.441863
931                             100.467068
993                              -0.908881
1364                             -0.010885

======================================================================
Employment Outcomes Score
Invalid values: 63
                              University  Employment Outcomes Score
1794  California Institute of Technology                 101.564348
1903          Carnegie Mellon University                 119.449347
2568                 Columbia University                 109.454752
2634                  Cornell University                 104.542565
3119                          ETH Zurich                 114.966417
3820                    Fudan University                 102.571013
3871         GMR Institute of Technology                  -0.402364
3998     Georgia Institute of Technology                 108.624056
4422                  Harvard University                 102.057420
4424                  Harvard University                 101.976888

======================================================================
Sustainability Score
Invalid values: 543
                                            University  Sustainability Score
139                       Acharya Nagarjuna University             -2.566587
145                                Acıbadem University             -5.449203
146                                Acıbadem University             -6.224790
161  Adana Alparslan Türkeş Science and Technology ...            -14.135916
170                                 Adelphi University             -1.425841
197                           Aichi Medical University             -7.757206
198                           Aichi Medical University             -5.294065
199                           Aichi Medical University             -6.166738
200                           Aichi Medical University            -11.581464
201                           Aichi Medical University             -6.103806

======================================================================
Research Environment
Invalid values: 10
                                              University  Research Environment
836          Athens University of Economics And Business             -2.938487
2272       China University of Political Science and Law            -19.479683
4742                                       IE University             -6.452281
6868     Lahore University of Management Sciences (LUMS)             -4.940115
8608   National Technical University of Ukraine "Igor...             -0.424342
12331        Symbiosis International (Deemed University)            -20.232326
13584              Tokyo University of Science (RIKADAI)             -7.213261
14488            Universidad Nacional de Ingeniería Peru             -0.596950
14658                    Universidad Pontificia Comillas            -14.642163
21603                               Universität Mannheim             -3.420664

======================================================================
Research Quality
Invalid values: 20
                                              University  Research Quality
572                   Amirkabir University of Technology        108.954057
3065                                  Duy Tan University        110.631518
3776                            Freie Universität Berlin        106.413092
6358                    King Abdul Aziz University (KAU)        109.432708
7242                                    MGIMO University         -3.109528
8159                                  Nanjing University        107.431562
8962                     North Carolina State University        103.681904
10009  Pontificia Universidad Católica Argentina Sant...         -3.542421
10164                                    Pratt Institute         -9.316142
10179                           Prince Sultan University        100.743825

======================================================================
Industry Impact
Invalid values: 37
                                             University  Industry Impact
1527                                 Birzeit university        -0.396498
1804       California Institute of Technology (Caltech)       100.799306
1827                       Canadian University of Dubai        -4.414686
2272      China University of Political Science and Law       -29.673812
2440                       City University of Hong Kong       109.471409
4034                         German university in Cairo       -10.467193
4927  Indian Institute of Information Technology - A...        -4.987990
5790                           Johns Hopkins University       115.863892
6497                        King's College London (KCL)       101.809602
7511        Massachusetts Institute of Technology (MIT)       109.674573

======================================================================
International Outlook
Invalid values: 5
                                University  International Outlook
1827          Canadian University of Dubai             102.599685
9623   Paris Lodron University of Salzburg             100.994748
10336           Queen's University Belfast             106.495802
20809                 University of Ulster             103.551511
22317      Vienna University of Technology             100.061431

In [38]:
# ==========================================
# Final Data Validation
# ==========================================

# Score columns (0-100)
score_columns = [
    "Academic Reputation Score",
    "Employer Reputation Score",
    "Faculty Student Score",
    "Citations per Faculty Score",
    "International Faculty Score",
    "International Students Score",
    "International Research Network Score",
    "Employment Outcomes Score",
    "Sustainability Score",
    "Teaching",
    "Research Environment",
    "Research Quality",
    "Industry Impact",
    "International Outlook"
]

# Count columns (>=0)
count_columns = [
    "Student Population",
    "International Students",
    "Publications",
    "Citation Count",
    "h-index"
]

# Ratio column
ratio_columns = [
    "Students to Staff Ratio"
]

# Clip score columns
for col in score_columns:
    if col in df.columns:
        df[col] = df[col].clip(0, 100)

# Clip count columns
for col in count_columns:
    if col in df.columns:
        df[col] = df[col].clip(lower=0)

# Clip ratios
for col in ratio_columns:
    if col in df.columns:
        df[col] = df[col].clip(lower=0)

print("=" * 60)
print("DATA VALIDATION COMPLETED")
print("=" * 60)
print("✓ Scores clipped to 0-100")
print("✓ Counts clipped to >= 0")
print("✓ Ratios clipped to >= 0")

============================================================
DATA VALIDATION COMPLETED
============================================================
✓ Scores clipped to 0-100
✓ Counts clipped to >= 0
✓ Ratios clipped to >= 0

In [39]:
# ==========================================
# Top Remaining Missing Columns
# ==========================================

remaining = (

    df.isna()

      .sum()

      .sort_values(ascending=False)

      .to_frame("Missing")

)

remaining["Missing %"] = (

    remaining["Missing"]

    / len(df)

    * 100

).round(2)

display(

    remaining.head(25)

)

                                      Missing  Missing %
City                                      454       1.95
University Type                           395       1.70
Research Output                           395       1.70
University Age Band                       250       1.07
Subject Area                                6       0.03
Country Code                                4       0.02
University                                  0       0.00
Country                                     0       0.00
Employer Reputation Score                   0       0.00
Faculty Student Score                       0       0.00
Citations per Faculty Score                 0       0.00
Region                                      0       0.00
International Faculty Score                 0       0.00
International Students Score                0       0.00
Employment Outcomes Score                   0       0.00
International Research Network Score        0       0.00
Sustainability Score                        0       0.00
Faculty Count                               0       0.00
Year                                        0       0.00
Academic Reputation Score                   0       0.00
Student Population                          0       0.00
Teaching                                    0       0.00
Research Quality                            0       0.00
Research Environment                        0       0.00
International Outlook                       0       0.00

In [40]:
# ==========================================
# Export Final Dataset
# ==========================================

OUTPUT_PATH.mkdir(parents=True, exist_ok=True)

df.to_csv(
    OUTPUT_FILE,
    index=False
)

print("=" * 60)
print("MODULE 2 COMPLETED")
print("=" * 60)
print(f"Saved : {OUTPUT_FILE}")

============================================================
MODULE 2 COMPLETED
============================================================
Saved : c:\Users\shashank\Desktop\Infosys SpringBoard\higher-education-dv\datasets\final\Module_2_Deliverables\university_cleaned.csv

In [42]:
# ==========================================
# Final Module 2 Summary
# ==========================================

verify_df = df.copy()

missing = verify_df.isna().sum().sum()
cells = verify_df.shape[0] * verify_df.shape[1]

missing_percentage = (missing / cells) * 100
completeness = 100 - missing_percentage

negative_values = (
    verify_df.select_dtypes(include="number") < 0
).sum().sum()

print("=" * 70)
print("MODULE 2 SUMMARY")
print("=" * 70)

print(f"Rows                 : {len(verify_df):,}")
print(f"Columns              : {verify_df.shape[1]}")
print(f"Missing Values       : {missing:,}")
print(f"Missing Percentage   : {missing_percentage:.2f}%")
print(f"Completeness         : {completeness:.2f}%")
print(f"Negative Values      : {negative_values}")
print(f"Numeric Validation    : Passed")

======================================================================
MODULE 2 SUMMARY
======================================================================
Rows                 : 23,263
Columns              : 36
Missing Values       : 1,504
Missing Percentage   : 0.18%
Completeness         : 99.82%
Negative Values      : 0
Numeric Validation    : Passed