In [11]:
import pandas as pd
from pathlib import Path

In [12]:
PROJECT_ROOT = Path(r"C:\Users\ASUS\Desktop\higher-education-dv")

RAW_DATA = PROJECT_ROOT / "data" / "raw"

In [13]:
qs_history = pd.read_csv(RAW_DATA / "qs_rankings_2017_2022_raw.csv")

qs_2024 = pd.read_csv(RAW_DATA / "qs_rankings_2024_raw.csv")

the_2020 = pd.read_csv(RAW_DATA / "2020_rankings.csv")
the_2021 = pd.read_csv(RAW_DATA / "2021_rankings.csv")
the_2022 = pd.read_csv(RAW_DATA / "2022_rankings.csv")
the_2023 = pd.read_csv(RAW_DATA / "2023_rankings.csv")
the_2024 = pd.read_csv(RAW_DATA / "2024_rankings.csv")

In [14]:
def audit_dataset(df, dataset_name):

    print("=" * 80)
    print(dataset_name)
    print("=" * 80)

    print(f"\nShape : {df.shape}")

    print("\nColumns")
    print(df.columns.tolist())

    print("\nData Types")
    print(df.dtypes)

    print("\nMissing Values")
    print(df.isnull().sum())

    print("\nDuplicate Rows")
    print(df.duplicated().sum())

    print("\nFirst Five Rows")
    display(df.head())

In [15]:
audit_dataset(qs_history, "QS 2017-2022")

audit_dataset(qs_2024, "QS 2024")

audit_dataset(the_2020, "THE 2020")

audit_dataset(the_2021, "THE 2021")

audit_dataset(the_2022, "THE 2022")

audit_dataset(the_2023, "THE 2023")

audit_dataset(the_2024, "THE 2024")

================================================================================
QS 2017-2022
================================================================================

Shape : (6482, 15)

Columns
['university', 'year', 'rank_display', 'score', 'link', 'country', 'city', 'region', 'logo', 'type', 'research_output', 'student_faculty_ratio', 'international_students', 'size', 'faculty_count']

Data Types
university                 object
year                        int64
rank_display               object
score                     float64
link                       object
country                    object
city                       object
region                     object
logo                       object
type                       object
research_output            object
student_faculty_ratio     float64
international_students     object
size                       object
faculty_count              object
dtype: object

Missing Values
university                   0
year                         0
rank_display                68
score                     3662
link                         0
country                      0
city                       178
region                       0
logo                         0
type                        12
research_output              2
student_faculty_ratio       75
international_students     164
size                         2
faculty_count               78
dtype: int64

Duplicate Rows
0

First Five Rows

,university,year,rank_display,score,link,country,city,region,logo,type,research_output,student_faculty_ratio,international_students,size,faculty_count
0,Massachusetts Institute of Technology (MIT),2017,1,100.0,https://www.topuniversities.com/universities/m...,United States,Cambridge,North America,https://www.topuniversities.com/sites/default/...,Private,Very High,4.0,"3,730",M,"3,065"
1,Stanford University,2017,2,98.7,https://www.topuniversities.com/universities/s...,United States,Stanford,North America,https://www.topuniversities.com/sites/default/...,Private,Very High,3.0,"3,879",L,"4,725"
2,Harvard University,2017,3,98.3,https://www.topuniversities.com/universities/h...,United States,Cambridge,North America,https://www.topuniversities.com/sites/default/...,Private,Very High,5.0,"5,877",L,"4,646"
3,University of Cambridge,2017,4,97.2,https://www.topuniversities.com/universities/u...,United Kingdom,Cambridge,Europe,https://www.topuniversities.com/sites/default/...,Public,Very high,4.0,"7,925",L,"5,800"
4,California Institute of Technology (Caltech),2017,5,96.9,https://www.topuniversities.com/universities/c...,United States,Pasadena,North America,https://www.topuniversities.com/sites/default/...,Private,Very High,2.0,692,S,968

================================================================================
QS 2024
================================================================================

Shape : (1498, 29)

Columns
['2024 RANK', '2023 RANK', 'Institution Name', 'Country Code', 'Country', 'SIZE', 'FOCUS', 'RES.', 'AGE', 'STATUS', 'Academic Reputation Score', 'Academic Reputation Rank', 'Employer Reputation Score', 'Employer Reputation Rank', 'Faculty Student Score', 'Faculty Student Rank', 'Citations per Faculty Score', 'Citations per Faculty Rank', 'International Faculty Score', 'International Faculty Rank', 'International Students Score', 'International Students Rank', 'International Research Network Score', 'International Research Network Rank', 'Employment Outcomes Score', 'Employment Outcomes Rank', 'Sustainability Score', 'Sustainability Rank', 'Overall SCORE']

Data Types
2024 RANK                               object
2023 RANK                               object
Institution Name                        object
Country Code                            object
Country                                 object
SIZE                                    object
FOCUS                                   object
RES.                                    object
AGE                                     object
STATUS                                  object
Academic Reputation Score               object
Academic Reputation Rank                object
Employer Reputation Score               object
Employer Reputation Rank                object
Faculty Student Score                   object
Faculty Student Rank                    object
Citations per Faculty Score             object
Citations per Faculty Rank              object
International Faculty Score             object
International Faculty Rank              object
International Students Score            object
International Students Rank             object
International Research Network Score    object
International Research Network Rank     object
Employment Outcomes Score               object
Employment Outcomes Rank                object
Sustainability Score                    object
Sustainability Rank                     object
Overall SCORE                           object
dtype: object

Missing Values
2024 RANK                                 0
2023 RANK                                82
Institution Name                          0
Country Code                              0
Country                                   0
SIZE                                     23
FOCUS                                     1
RES.                                     87
AGE                                      26
STATUS                                   42
Academic Reputation Score                 0
Academic Reputation Rank                  0
Employer Reputation Score                 1
Employer Reputation Rank                  1
Faculty Student Score                    24
Faculty Student Rank                     24
Citations per Faculty Score              24
Citations per Faculty Rank               24
International Faculty Score             126
International Faculty Rank              126
International Students Score             80
International Students Rank              80
International Research Network Score      4
International Research Network Rank       4
Employment Outcomes Score                24
Employment Outcomes Rank                 24
Sustainability Score                    100
Sustainability Rank                     100
Overall SCORE                             0
dtype: int64

Duplicate Rows
0

First Five Rows

,2024 RANK,2023 RANK,Institution Name,Country Code,Country,SIZE,FOCUS,RES.,AGE,STATUS,...,International Faculty Rank,International Students Score,International Students Rank,International Research Network Score,International Research Network Rank,Employment Outcomes Score,Employment Outcomes Rank,Sustainability Score,Sustainability Rank,Overall SCORE
0,rank display,rank display2,institution,location code,location,size,focus,research,age band,status,...,ifr rank,isr score,isr rank,irn score,irn rank,ger score,ger rank,SUS SCORE,SUS RANK,Overall Score
1,1,1,Massachusetts Institute of Technology (MIT),US,United States,M,CO,VH,5,B,...,56,88.2,128,94.3,58,100,4,95.2,51,100.0
2,2,2,University of Cambridge,UK,United Kingdom,L,FC,VH,5,A,...,64,95.8,85,99.9,7,100,6,97.3,33=,99.2
3,3,4,University of Oxford,UK,United Kingdom,L,FC,VH,5,A,...,110,98.2,60,100.0,1,100,3,97.8,26=,98.9
4,4,5,Harvard University,US,United States,L,FC,VH,5,B,...,210,66.8,223,100.0,5,100,1,96.7,39,98.3

================================================================================
THE 2020
================================================================================

Shape : (1397, 24)

Columns
['rank_order', 'rank', 'name', 'scores_overall', 'scores_overall_rank', 'scores_teaching', 'scores_teaching_rank', 'scores_research', 'scores_research_rank', 'scores_citations', 'scores_citations_rank', 'scores_industry_income', 'scores_industry_income_rank', 'scores_international_outlook', 'scores_international_outlook_rank', 'location', 'stats_number_students', 'stats_student_staff_ratio', 'stats_pc_intl_students', 'stats_female_male_ratio', 'aliases', 'subjects_offered', 'closed', 'unaccredited']

Data Types
rank_order                             int64
rank                                  object
name                                  object
scores_overall                        object
scores_overall_rank                    int64
scores_teaching                      float64
scores_teaching_rank                   int64
scores_research                      float64
scores_research_rank                   int64
scores_citations                     float64
scores_citations_rank                  int64
scores_industry_income               float64
scores_industry_income_rank            int64
scores_international_outlook         float64
scores_international_outlook_rank      int64
location                              object
stats_number_students                 object
stats_student_staff_ratio            float64
stats_pc_intl_students                object
stats_female_male_ratio               object
aliases                               object
subjects_offered                      object
closed                                  bool
unaccredited                            bool
dtype: object

Missing Values
rank_order                            0
rank                                  0
name                                  0
scores_overall                        0
scores_overall_rank                   0
scores_teaching                       0
scores_teaching_rank                  0
scores_research                       0
scores_research_rank                  0
scores_citations                      0
scores_citations_rank                 0
scores_industry_income                0
scores_industry_income_rank           0
scores_international_outlook          0
scores_international_outlook_rank     0
location                              0
stats_number_students                 0
stats_student_staff_ratio             0
stats_pc_intl_students                0
stats_female_male_ratio              66
aliases                               0
subjects_offered                      0
closed                                0
unaccredited                          0
dtype: int64

Duplicate Rows
0

First Five Rows

,rank_order,rank,name,scores_overall,scores_overall_rank,scores_teaching,scores_teaching_rank,scores_research,scores_research_rank,scores_citations,...,scores_international_outlook_rank,location,stats_number_students,stats_student_staff_ratio,stats_pc_intl_students,stats_female_male_ratio,aliases,subjects_offered,closed,unaccredited
0,10,1,University of Oxford,95.4,10,90.5,6,99.6,1,98.4,...,22,United Kingdom,"20,665",11.2,41%,46 : 54,University of Oxford,"Accounting & Finance,General Engineering,Commu...",False,False
1,20,2,California Institute of Technology,94.5,20,92.1,2,97.2,4,97.9,...,151,United States,"2,240",6.4,30%,34 : 66,California Institute of Technology caltech,"Languages, Literature & Linguistics,Economics ...",False,False
2,30,3,University of Cambridge,94.4,30,91.4,4,98.7,2,95.8,...,37,United Kingdom,"18,980",10.9,37%,47 : 53,University of Cambridge,"Business & Management,General Engineering,Art,...",False,False
3,40,4,Stanford University,94.3,40,92.8,1,96.4,5,99.9,...,188,United States,"16,135",7.3,23%,43 : 57,Stanford University,"Physics & Astronomy,Computer Science,Politics ...",False,False
4,50,5,Massachusetts Institute of Technology,93.6,50,90.5,5,92.4,10,99.5,...,99,United States,"11,247",8.6,34%,39 : 61,Massachusetts Institute of Technology,"Mathematics & Statistics,Languages, Literature...",False,False

================================================================================
THE 2021
================================================================================

Shape : (1526, 24)

Columns
['rank_order', 'rank', 'name', 'scores_overall', 'scores_overall_rank', 'scores_teaching', 'scores_teaching_rank', 'scores_research', 'scores_research_rank', 'scores_citations', 'scores_citations_rank', 'scores_industry_income', 'scores_industry_income_rank', 'scores_international_outlook', 'scores_international_outlook_rank', 'location', 'stats_number_students', 'stats_student_staff_ratio', 'stats_pc_intl_students', 'stats_female_male_ratio', 'aliases', 'subjects_offered', 'closed', 'unaccredited']

Data Types
rank_order                             int64
rank                                  object
name                                  object
scores_overall                        object
scores_overall_rank                    int64
scores_teaching                      float64
scores_teaching_rank                   int64
scores_research                      float64
scores_research_rank                   int64
scores_citations                     float64
scores_citations_rank                  int64
scores_industry_income               float64
scores_industry_income_rank            int64
scores_international_outlook         float64
scores_international_outlook_rank      int64
location                              object
stats_number_students                 object
stats_student_staff_ratio            float64
stats_pc_intl_students                object
stats_female_male_ratio               object
aliases                               object
subjects_offered                      object
closed                                  bool
unaccredited                            bool
dtype: object

Missing Values
rank_order                            0
rank                                  0
name                                  0
scores_overall                        0
scores_overall_rank                   0
scores_teaching                       0
scores_teaching_rank                  0
scores_research                       0
scores_research_rank                  0
scores_citations                      0
scores_citations_rank                 0
scores_industry_income                0
scores_industry_income_rank           0
scores_international_outlook          0
scores_international_outlook_rank     0
location                              0
stats_number_students                 0
stats_student_staff_ratio             0
stats_pc_intl_students                0
stats_female_male_ratio              73
aliases                               0
subjects_offered                      0
closed                                0
unaccredited                          0
dtype: int64

Duplicate Rows
0

First Five Rows

,rank_order,rank,name,scores_overall,scores_overall_rank,scores_teaching,scores_teaching_rank,scores_research,scores_research_rank,scores_citations,...,scores_international_outlook_rank,location,stats_number_students,stats_student_staff_ratio,stats_pc_intl_students,stats_female_male_ratio,aliases,subjects_offered,closed,unaccredited
0,10,1,University of Oxford,95.6,10,91.3,5,99.6,1,98.0,...,24,United Kingdom,"20,775",11.1,41%,46 : 54,University of Oxford,"Accounting & Finance,General Engineering,Commu...",False,False
1,20,2,Stanford University,94.9,20,92.2,3,96.7,6,99.9,...,200,United States,"16,223",7.4,23%,44 : 56,Stanford University,"Physics & Astronomy,Computer Science,Politics ...",False,False
2,30,3,Harvard University,94.8,30,94.4,1,98.8,3,99.4,...,218,United States,"21,261",9.3,25%,49 : 51,Harvard University,"Mathematics & Statistics,Civil Engineering,Lan...",False,False
3,40,4,California Institute of Technology,94.5,40,92.5,2,96.9,5,97.0,...,158,United States,"2,238",6.3,33%,36 : 64,California Institute of Technology caltech,"Languages, Literature & Linguistics,Economics ...",False,False
4,50,5,Massachusetts Institute of Technology,94.4,50,90.7,6,94.4,8,99.7,...,96,United States,"11,276",8.4,34%,39 : 61,Massachusetts Institute of Technology,"Mathematics & Statistics,Languages, Literature...",False,False

================================================================================
THE 2022
================================================================================

Shape : (2112, 24)

Columns
['rank_order', 'rank', 'name', 'scores_overall', 'scores_overall_rank', 'scores_teaching', 'scores_teaching_rank', 'scores_research', 'scores_research_rank', 'scores_citations', 'scores_citations_rank', 'scores_industry_income', 'scores_industry_income_rank', 'scores_international_outlook', 'scores_international_outlook_rank', 'location', 'stats_number_students', 'stats_student_staff_ratio', 'stats_pc_intl_students', 'stats_female_male_ratio', 'aliases', 'subjects_offered', 'closed', 'unaccredited']

Data Types
rank_order                             int64
rank                                  object
name                                  object
scores_overall                        object
scores_overall_rank                    int64
scores_teaching                      float64
scores_teaching_rank                   int64
scores_research                      float64
scores_research_rank                   int64
scores_citations                     float64
scores_citations_rank                  int64
scores_industry_income               float64
scores_industry_income_rank            int64
scores_international_outlook         float64
scores_international_outlook_rank      int64
location                              object
stats_number_students                 object
stats_student_staff_ratio            float64
stats_pc_intl_students                object
stats_female_male_ratio               object
aliases                               object
subjects_offered                      object
closed                                  bool
unaccredited                            bool
dtype: object

Missing Values
rank_order                             0
rank                                   0
name                                   0
scores_overall                       450
scores_overall_rank                    0
scores_teaching                      450
scores_teaching_rank                   0
scores_research                      450
scores_research_rank                   0
scores_citations                     450
scores_citations_rank                  0
scores_industry_income               450
scores_industry_income_rank            0
scores_international_outlook         450
scores_international_outlook_rank      0
location                               0
stats_number_students                  0
stats_student_staff_ratio              0
stats_pc_intl_students                 0
stats_female_male_ratio               79
aliases                                0
subjects_offered                       0
closed                                 0
unaccredited                           0
dtype: int64

Duplicate Rows
0

First Five Rows

,rank_order,rank,name,scores_overall,scores_overall_rank,scores_teaching,scores_teaching_rank,scores_research,scores_research_rank,scores_citations,...,scores_international_outlook_rank,location,stats_number_students,stats_student_staff_ratio,stats_pc_intl_students,stats_female_male_ratio,aliases,subjects_offered,closed,unaccredited
0,10,1,University of Oxford,95.7,10,91.0,5,99.6,1,98.0,...,26,United Kingdom,"20,835",10.7,42%,47 : 53,University of Oxford,"Accounting & Finance,General Engineering,Commu...",False,False
1,20,=2,California Institute of Technology,95.0,20,93.6,2,96.9,4,97.8,...,167,United States,"2,233",6.3,34%,36 : 64,California Institute of Technology caltech,"Languages, Literature & Linguistics,Economics ...",False,False
2,30,=2,Harvard University,95.0,30,94.5,1,98.9,3,99.2,...,209,United States,"21,574",9.5,24%,50 : 50,Harvard University,"Mathematics & Statistics,Civil Engineering,Lan...",False,False
3,40,4,Stanford University,94.9,40,92.3,3,96.8,5,99.9,...,211,United States,"16,319",7.3,23%,46 : 54,Stanford University,"Physics & Astronomy,Computer Science,Politics ...",False,False
4,50,=5,University of Cambridge,94.6,50,90.9,6,99.5,2,96.2,...,32,United Kingdom,"19,680",11.1,39%,47 : 53,University of Cambridge,"Business & Management,General Engineering,Art,...",False,False

================================================================================
THE 2023
================================================================================

Shape : (2345, 24)

Columns
['rank_order', 'rank', 'name', 'scores_overall', 'scores_overall_rank', 'scores_teaching', 'scores_teaching_rank', 'scores_research', 'scores_research_rank', 'scores_citations', 'scores_citations_rank', 'scores_industry_income', 'scores_industry_income_rank', 'scores_international_outlook', 'scores_international_outlook_rank', 'location', 'stats_number_students', 'stats_student_staff_ratio', 'stats_pc_intl_students', 'stats_female_male_ratio', 'aliases', 'subjects_offered', 'closed', 'unaccredited']

Data Types
rank_order                             int64
rank                                  object
name                                  object
scores_overall                        object
scores_overall_rank                    int64
scores_teaching                      float64
scores_teaching_rank                   int64
scores_research                      float64
scores_research_rank                   int64
scores_citations                     float64
scores_citations_rank                  int64
scores_industry_income               float64
scores_industry_income_rank            int64
scores_international_outlook         float64
scores_international_outlook_rank      int64
location                              object
stats_number_students                 object
stats_student_staff_ratio            float64
stats_pc_intl_students                object
stats_female_male_ratio               object
aliases                               object
subjects_offered                      object
closed                                  bool
unaccredited                            bool
dtype: object

Missing Values
rank_order                             0
rank                                   0
name                                   0
scores_overall                       546
scores_overall_rank                    0
scores_teaching                      546
scores_teaching_rank                   0
scores_research                      546
scores_research_rank                   0
scores_citations                     546
scores_citations_rank                  0
scores_industry_income               546
scores_industry_income_rank            0
scores_international_outlook         546
scores_international_outlook_rank      0
location                               0
stats_number_students                  0
stats_student_staff_ratio              1
stats_pc_intl_students                 0
stats_female_male_ratio               90
aliases                                0
subjects_offered                       6
closed                                 0
unaccredited                           0
dtype: int64

Duplicate Rows
0

First Five Rows

,rank_order,rank,name,scores_overall,scores_overall_rank,scores_teaching,scores_teaching_rank,scores_research,scores_research_rank,scores_citations,...,scores_international_outlook_rank,location,stats_number_students,stats_student_staff_ratio,stats_pc_intl_students,stats_female_male_ratio,aliases,subjects_offered,closed,unaccredited
0,10,1,University of Oxford,96.4,10,92.3,5,99.7,1,99.0,...,28,United Kingdom,"20,965",10.6,42%,48 : 52,University of Oxford,"Accounting & Finance,General Engineering,Commu...",False,False
1,20,2,Harvard University,95.2,20,94.8,1,99.0,3,99.3,...,214,United States,"21,887",9.6,25%,50 : 50,Harvard University,"Mathematics & Statistics,Civil Engineering,Lan...",False,False
2,30,=3,University of Cambridge,94.8,30,90.9,7,99.5,2,97.0,...,34,United Kingdom,"20,185",11.3,39%,47 : 53,University of Cambridge,"Business & Management,General Engineering,Art,...",False,False
3,40,=3,Stanford University,94.8,40,94.2,2,96.7,7,99.8,...,223,United States,"16,164",7.1,24%,46 : 54,Stanford University,"Physics & Astronomy,Computer Science,Politics ...",False,False
4,50,5,Massachusetts Institute of Technology,94.2,50,90.7,8,93.6,11,99.8,...,119,United States,"11,415",8.2,33%,40 : 60,Massachusetts Institute of Technology,"Mathematics & Statistics,Languages, Literature...",False,False

================================================================================
THE 2024
================================================================================

Shape : (2671, 25)

Columns
['rank_order', 'rank', 'name', 'scores_overall', 'scores_overall_rank', 'scores_teaching', 'scores_teaching_rank', 'scores_research', 'scores_research_rank', 'scores_citations', 'scores_citations_rank', 'scores_industry_income', 'scores_industry_income_rank', 'scores_international_outlook', 'scores_international_outlook_rank', 'location', 'stats_number_students', 'stats_student_staff_ratio', 'stats_pc_intl_students', 'stats_female_male_ratio', 'stats_proportion_of_isr', 'aliases', 'subjects_offered', 'closed', 'unaccredited']

Data Types
rank_order                             int64
rank                                  object
name                                  object
scores_overall                        object
scores_overall_rank                    int64
scores_teaching                      float64
scores_teaching_rank                   int64
scores_research                      float64
scores_research_rank                   int64
scores_citations                     float64
scores_citations_rank                  int64
scores_industry_income               float64
scores_industry_income_rank            int64
scores_international_outlook         float64
scores_international_outlook_rank      int64
location                              object
stats_number_students                 object
stats_student_staff_ratio            float64
stats_pc_intl_students                object
stats_female_male_ratio               object
stats_proportion_of_isr               object
aliases                               object
subjects_offered                      object
closed                                  bool
unaccredited                            bool
dtype: object

Missing Values
rank_order                             0
rank                                   0
name                                   0
scores_overall                       765
scores_overall_rank                    0
scores_teaching                      765
scores_teaching_rank                   0
scores_research                      765
scores_research_rank                   0
scores_citations                     765
scores_citations_rank                  0
scores_industry_income               765
scores_industry_income_rank            0
scores_international_outlook         765
scores_international_outlook_rank      0
location                               1
stats_number_students                  0
stats_student_staff_ratio              0
stats_pc_intl_students                 0
stats_female_male_ratio               93
stats_proportion_of_isr              217
aliases                                0
subjects_offered                       4
closed                                 0
unaccredited                           0
dtype: int64

Duplicate Rows
0

First Five Rows

,rank_order,rank,name,scores_overall,scores_overall_rank,scores_teaching,scores_teaching_rank,scores_research,scores_research_rank,scores_citations,...,location,stats_number_students,stats_student_staff_ratio,stats_pc_intl_students,stats_female_male_ratio,stats_proportion_of_isr,aliases,subjects_offered,closed,unaccredited
0,10,1,University of Oxford,98.5,10,96.6,5,100.0,2,99.0,...,United Kingdom,"21,750",10.9,42%,49 : 51,23%,University of Oxford,"Geography,Chemistry,Chemical Engineering,Biolo...",False,False
1,20,2,Stanford University,98.0,20,99.0,1,97.8,8,99.6,...,United States,"14,517",6.4,23%,47 : 53,22%,Stanford University,"Computer Science,Communication & Media Studies...",False,False
2,30,3,Massachusetts Institute of Technology,97.9,30,98.6,2,96.2,11,99.7,...,United States,"11,085",8.0,33%,41 : 59,40%,Massachusetts Institute of Technology,"Architecture,Economics & Econometrics,Archaeol...",False,False
3,40,4,Harvard University,97.8,40,97.7,3,99.9,3,99.4,...,United States,"20,050",9.0,25%,51 : 49,12%,Harvard University,"Sociology,Architecture,Physics & Astronomy,Psy...",False,False
4,50,5,University of Cambridge,97.5,50,95.8,7,100.0,1,98.0,...,United Kingdom,"20,565",11.5,38%,48 : 52,27%,University of Cambridge,Politics & International Studies (incl Develop...,False,False

In [16]:
print("QS 2017-2022 :", qs_history["university"].nunique())

print("QS 2024 :", qs_2024["Institution Name"].nunique())

print("THE 2024 :", the_2024["name"].nunique())

QS 2017-2022 : 1368
QS 2024 : 1498
THE 2024 : 2671

In [17]:
print("QS History Countries :", qs_history["country"].nunique())

print("QS 2024 Countries :", qs_2024["Country"].nunique())

print("THE Countries :", the_2024["location"].nunique())

QS History Countries : 97
QS 2024 Countries : 105
THE Countries : 127

In [18]:
print(qs_history["university"].sample(20, random_state=42).tolist())

print(qs_2024["Institution Name"].sample(20, random_state=42).tolist())

print(the_2024["name"].sample(20, random_state=42).tolist())

['Universidad de Sevilla', 'University of New England Australia', 'Victoria University of Wellington', 'Universität Konstanz', 'University of Delaware', 'Universidad Politécnica de Madrid (UPM)', 'Boston University', 'Swinburne University of Technology', 'Université de Lorraine', 'United Arab Emirates University', 'London Metropolitan University', 'Nanjing University', 'V. N. Karazin Kharkiv National University', 'Tsinghua University', 'Queensland University of Technology (QUT)', 'University of Bristol', 'Missouri University of Science and Technology', 'University of Bergen', 'Universidad de La Habana', 'Koç University']
['Dankook University ', 'Suranaree University of Technology ', 'Shahjalal University of Science and Technology', 'University of Kragujevac', 'The Catholic University of Korea ', 'Nanjing Agricultural University', 'Universidad Peruana Cayetano Heredia (UPCH)', 'University of South Africa', 'Brunel University London', 'University of Surrey', "Universita' degli Studi di Ferrara", 'Universidad de Monterrey (UDEM)', 'Universidad Michoacana de San Nicolás de Hidalgo', 'University of Central Oklahoma', 'City University of Hong Kong', 'Indian Institute of Technology Kharagpur (IIT-KGP)', 'Jouf University', 'University of Peshawar', 'Essex, University of', 'Shanghai Jiao Tong University']
['École National Polytechnique de Constantine', 'University of Al-Qadisiyah', 'Thiagarajar College of Engineering', 'Université 8 Mai 1945 Guelma', 'Budapest University of Technology and Economics', 'Turan-Astana University', 'Al-Farabi Kazakh National University', 'Chalmers University of Technology', 'University for the Creative Arts', 'Kabarak University', 'SIMAD University', 'Saint Petersburg State Pediatric Medical University', 'University of Mysore', 'University of Wales Trinity Saint David', 'Istanbul Arel University', 'Istanbul University', 'Mohammed V University of Rabat', 'Balochistan University of Information Technology, Engineering and Management Sciences (BUITEMS)', 'University of Engineering and Technology, Taxila', 'TU Wien']

In [19]:
from pathlib import Path

print(Path.cwd())

c:\Users\ASUS\Desktop\higher-education-dv\notebooks

In [20]:
import pandas as pd

df = pd.read_csv("../data/raw/openalex_bulk_raw.csv")

print(df.shape)
print(df["institution_type"].value_counts())

(24761, 9)
institution_type
education    24761
Name: count, dtype: int64

In [21]:
print(df.shape)

(24761, 9)

In [22]:
df[df["openalex_display_name"].str.contains(
    "Massachusetts",
    case=False,
    na=False
)].head(10)

,institution_id,openalex_display_name,country_code,institution_type,works_count,cited_by_count,h_index,i10_index,2yr_mean_citedness
6146,https://openalex.org/I4210158860,University of Massachusetts Donahue Institute,US,education,50,1511,21,33,0.880000
6510,https://openalex.org/I4210113572,Massachusetts School Nurse Research Network,US,education,85,906,15,29,0.950000
7444,https://openalex.org/I55200170,Massachusetts College of Art and Design,US,education,277,2591,28,68,0.176471
9703,https://openalex.org/I2801721035,Massachusetts School of Law,US,education,743,5282,35,79,0.150000
10050,https://openalex.org/I26321052,Massachusetts College of Liberal Arts,US,education,712,15142,58,276,0.647887
11702,https://openalex.org/I165817395,Massachusetts College of Pharmacy and Health S...,US,education,4939,180981,170,3347,2.484024
15207,https://openalex.org/I100633361,University of Massachusetts Dartmouth,US,education,11562,461548,235,7547,3.740083
16191,https://openalex.org/I133738476,University of Massachusetts Lowell,US,education,26066,1210763,340,19853,2.843563
16278,https://openalex.org/I21294169,Massachusetts Maritime Academy,US,education,505,12902,58,234,1.623762
17656,https://openalex.org/I24603500,University of Massachusetts Amherst,US,education,124759,11096242,890,128769,4.520219

In [24]:
import pandas as pd

# Load datasets
registry = pd.read_csv("../data/interim/registry/university_registry.csv")
openalex = pd.read_csv("../data/raw/openalex_bulk_raw.csv")

# Normalize names in the same way
registry_names = registry["normalized_name"]

openalex_names = (
    openalex["openalex_display_name"]
    .fillna("")
    .str.lower()
    .str.strip()
)

# Count exact matches
matched = registry_names.isin(openalex_names)

print("=" * 50)
print("Registry Universities :", len(registry))
print("Exact Matches         :", matched.sum())
print("Coverage              :",
      round(matched.sum() / len(registry) * 100, 2), "%")
print("=" * 50)

==================================================
Registry Universities : 3565
Exact Matches         : 2059
Coverage              : 57.76 %
==================================================

In [1]:
import pandas as pd

df = pd.read_csv("../data/processed/openalex_master.csv")
print(df.columns.tolist())

['university_id', 'university_name', 'country', 'openalex_name', 'institution_id', 'works_count', 'cited_by_count', 'h_index', 'i10_index', '2yr_mean_citedness', 'matched_name', 'score']

In [2]:
df = pd.read_csv("../data/raw/worldbank_indicators_raw.csv")
print(df.columns.tolist())

['country_code', 'country_name', 'year', 'gdp_per_capita_usd', 'education_expenditure_pct_gdp', 'tertiary_enrollment_ratio', 'population', 'literacy_rate_pct', 'data_source', 'download_timestamp_utc']

In [3]:
df = pd.read_csv("../data/interim/normalized/qs_rankings_2024_raw_normalized.csv")
print(df.columns.tolist())

['2024 RANK', '2023 RANK', 'Institution Name', 'Country Code', 'Country', 'SIZE', 'FOCUS', 'RES.', 'AGE', 'STATUS', 'Academic Reputation Score', 'Academic Reputation Rank', 'Employer Reputation Score', 'Employer Reputation Rank', 'Faculty Student Score', 'Faculty Student Rank', 'Citations per Faculty Score', 'Citations per Faculty Rank', 'International Faculty Score', 'International Faculty Rank', 'International Students Score', 'International Students Rank', 'International Research Network Score', 'International Research Network Rank', 'Employment Outcomes Score', 'Employment Outcomes Rank', 'Sustainability Score', 'Sustainability Rank', 'Overall SCORE', 'normalized_name']

In [4]:
df = pd.read_csv("../data/interim/normalized/2024_rankings_normalized.csv")
print(df.columns.tolist())

['rank_order', 'rank', 'name', 'scores_overall', 'scores_overall_rank', 'scores_teaching', 'scores_teaching_rank', 'scores_research', 'scores_research_rank', 'scores_citations', 'scores_citations_rank', 'scores_industry_income', 'scores_industry_income_rank', 'scores_international_outlook', 'scores_international_outlook_rank', 'location', 'stats_number_students', 'stats_student_staff_ratio', 'stats_pc_intl_students', 'stats_female_male_ratio', 'stats_proportion_of_isr', 'aliases', 'subjects_offered', 'closed', 'unaccredited', 'normalized_name']

In [1]:
import pandas as pd

qs = pd.read_csv("../data/processed/qs_master.csv")
print(qs.shape)
print(qs.columns.tolist())

(7980, 46)
['university', 'year', 'rank_display', 'score', 'link', 'country', 'city', 'region', 'logo', 'type', 'research_output', 'student_faculty_ratio', 'international_students', 'size', 'faculty_count', 'normalized_name', 'university_id', '2024 RANK', '2023 RANK', 'Institution Name', 'Country Code', 'Country', 'SIZE', 'FOCUS', 'RES.', 'AGE', 'STATUS', 'Academic Reputation Score', 'Academic Reputation Rank', 'Employer Reputation Score', 'Employer Reputation Rank', 'Faculty Student Score', 'Faculty Student Rank', 'Citations per Faculty Score', 'Citations per Faculty Rank', 'International Faculty Score', 'International Faculty Rank', 'International Students Score', 'International Students Rank', 'International Research Network Score', 'International Research Network Rank', 'Employment Outcomes Score', 'Employment Outcomes Rank', 'Sustainability Score', 'Sustainability Rank', 'Overall SCORE']

In [2]:
the = pd.read_csv("../data/processed/the_master.csv")
print(the.shape)
print(the.columns.tolist())

(10051, 28)
['rank_order', 'rank', 'name', 'scores_overall', 'scores_overall_rank', 'scores_teaching', 'scores_teaching_rank', 'scores_research', 'scores_research_rank', 'scores_citations', 'scores_citations_rank', 'scores_industry_income', 'scores_industry_income_rank', 'scores_international_outlook', 'scores_international_outlook_rank', 'location', 'stats_number_students', 'stats_student_staff_ratio', 'stats_pc_intl_students', 'stats_female_male_ratio', 'aliases', 'subjects_offered', 'closed', 'unaccredited', 'normalized_name', 'year', 'university_id', 'stats_proportion_of_isr']

In [3]:
oa = pd.read_csv("../data/processed/openalex_master.csv")
print(oa.shape)
print(oa.columns.tolist())

(2865, 12)
['university_id', 'university_name', 'country', 'openalex_name', 'institution_id', 'works_count', 'cited_by_count', 'h_index', 'i10_index', '2yr_mean_citedness', 'matched_name', 'score']

In [4]:
wb = pd.read_csv("../data/raw/worldbank_indicators_raw.csv")
print(wb.shape)
print(wb.columns.tolist())

(1250, 10)
['country_code', 'country_name', 'year', 'gdp_per_capita_usd', 'education_expenditure_pct_gdp', 'tertiary_enrollment_ratio', 'population', 'literacy_rate_pct', 'data_source', 'download_timestamp_utc']