In [1]:
import pandas as pd

In [2]:
world = pd.read_csv(r"C:\Users\yadav\higher-education-dv\datasets\raw_data\WORLD UNIVERSITY RANKINGS.csv")

qs2024 = pd.read_csv(r"C:\Users\yadav\higher-education-dv\datasets\raw_data\2024 QS World University Rankings 1.1 (For qs.com).csv")

cwur = pd.read_csv(r"C:\Users\yadav\higher-education-dv\datasets\raw_data\cwurData.csv")

list_uni = pd.read_csv(r"C:\Users\yadav\higher-education-dv\datasets\raw_data\list_of_universities.csv")

qs2024_full = pd.read_csv(r"C:\Users\yadav\higher-education-dv\datasets\raw_data\QS 2024.csv")

qs_history = pd.read_csv(r"C:\Users\yadav\higher-education-dv\datasets\raw_data\qs-world-university-rankings-2017-to-2022-V2.csv")

the = pd.read_csv(r"C:\Users\yadav\higher-education-dv\datasets\raw_data\THE World University Rankings 2016-2026.csv")

top1000 = pd.read_csv(r"C:\Users\yadav\higher-education-dv\datasets\raw_data\Top 1000 Universities Worldwide.csv")

top100 = pd.read_csv(r"C:\Users\yadav\higher-education-dv\datasets\raw_data\top_100_universities_dataset.csv")

In [3]:
datasets = {
    "WORLD": world,
    "QS2024": qs2024,
    "CWUR": cwur,
    "LIST": list_uni,
    "QS_FULL": qs2024_full,
    "QS_HISTORY": qs_history,
    "THE": the,
    "TOP1000": top1000,
    "TOP100": top100
}

for name, df in datasets.items():
    print(f"\n{'='*60}")
    print(name)
    print("Shape:", df.shape)
    print("Columns:")
    print(df.columns.tolist())

============================================================
WORLD
Shape: (2000, 9)
Columns:
['World Rank', 'Institution', 'Location', 'National Rank', 'Education Rank', 'Employability Rank', 'Faculty Rank', 'Research Rank', 'Score']

============================================================
QS2024
Shape: (1498, 29)
Columns:
['2024 RANK', '2023 RANK', 'Institution Name', 'Country Code', 'Country', 'SIZE', 'FOCUS', 'RES.', 'AGE', 'STATUS', 'Academic Reputation Score', 'Academic Reputation Rank', 'Employer Reputation Score', 'Employer Reputation Rank', 'Faculty Student Score', 'Faculty Student Rank', 'Citations per Faculty Score', 'Citations per Faculty Rank', 'International Faculty Score', 'International Faculty Rank', 'International Students Score', 'International Students Rank', 'International Research Network Score', 'International Research Network Rank', 'Employment Outcomes Score', 'Employment Outcomes Rank', 'Sustainability Score', 'Sustainability Rank', 'Overall SCORE']

============================================================
CWUR
Shape: (2200, 14)
Columns:
['world_rank', 'institution', 'country', 'national_rank', 'quality_of_education', 'alumni_employment', 'quality_of_faculty', 'publications', 'influence', 'citations', 'broad_impact', 'patents', 'score', 'year']

============================================================
LIST
Shape: (9255, 5)
Columns:
['id', 'name', 'country', 'country_code', 'web_pages']

============================================================
QS_FULL
Shape: (675, 101)
Columns:
['university_id', '2024 RANK', '2023 RANK', 'University', 'Country Code', 'Country_x', 'SIZE', 'FOCUS', 'RES.', 'AGE', 'STATUS', 'Academic Reputation Score', 'Academic Reputation Rank', 'Employer Reputation Score', 'Employer Reputation Rank', 'Faculty Student Score', 'Faculty Student Rank', 'Citations per Faculty Score', 'Citations per Faculty Rank', 'International Faculty Score', 'International Faculty Rank', 'International Students Score', 'International Students Rank', 'International Research Network Score', 'International Research Network Rank', 'Employment Outcomes Score', 'Employment Outcomes Rank', 'Sustainability Score', 'Sustainability Rank', 'Overall SCORE', 'Rank', 'Student Population', 'Students to Staff Ratio', 'International Students', 'Female to Male Ratio', 'Overall Score', 'Teaching', 'Research Environment', 'Research Quality', 'Industry Impact', 'International Outlook', 'Year', 'World Rank', 'Location', 'National_Rank_x', 'Quality of Education', 'Alumni Employment', 'Quality of Faculty', 'Research_Output_x', 'Quality_Publications', 'Influence', 'Citations_Count', 'Score', 'Latitude', 'Longitude', 'city_x', 'region_x', 'type_x', 'research_output_x', 'student_faculty_ratio_x', 'faculty_count_x', 'city_y', 'region_y', 'type_y', 'research_output_y', 'student_faculty_ratio_y', 'faculty_count_y', 'city', 'region', 'type', 'research_output', 'student_faculty_ratio', 'faculty_count', 'universities_ranked_count', 'best_university_rank', 'country_avg_overall_score', 'country_avg_academic_reputation', 'country_avg_rank', 'country_avg_citations', 'country_avg_international_ratio', 'research_productivity_index', 'female_percentage', 'male_percentage', 'subject_field', 'citations_score', 'research_output_score', 'Enrollment', 'Undergrad_Students', 'Postgrad_Students', 'Faculty_Count', 'Student_Faculty_Ratio', 'Research_Output', 'International_Students (%)', 'Tuition_Fee_USD', 'Acceptance_Rate (%)', 'Graduation_Rate (%)', 'Employability_Rank', 'QS_Subject_Rank', 'QS_Rank', 'THE_Rank', 'ARWU_Rank']

============================================================
QS_HISTORY
Shape: (6482, 15)
Columns:
['university', 'year', 'rank_display', 'score', 'link', 'country', 'city', 'region', 'logo', 'type', 'research_output', 'student_faculty_ratio', 'international_students', 'size', 'faculty_count']

============================================================
THE
Shape: (16713, 14)
Columns:
['Rank', 'Name', 'Country', 'Student Population', 'Students to Staff Ratio', 'International Students', 'Female to Male Ratio', 'Overall Score', 'Teaching', 'Research Environment', 'Research Quality', 'Industry Impact', 'International Outlook', 'Year']

============================================================
TOP1000
Shape: (1000, 19)
Columns:
['Country', 'University_Name', 'World_Rank', 'National_Rank', 'QS_Rank', 'THE_Rank', 'ARWU_Rank', 'Enrollment', 'Undergrad_Students', 'Postgrad_Students', 'Faculty_Count', 'Student_Faculty_Ratio', 'Research_Output', 'International_Students (%)', 'Tuition_Fee_USD', 'Acceptance_Rate (%)', 'Graduation_Rate (%)', 'Employability_Rank', 'QS_Subject_Rank']

============================================================
TOP100
Shape: (100, 10)
Columns:
['Position', 'University_Name', 'Location', 'Established_Year', 'Total_Students', 'Number_of_Campuses', 'Programs_Offered', 'University_Type', 'Total_Faculty', 'Campus_Area_Acres']

In [4]:
# WORLD
world.rename(columns={
    'Institution':'University_Name',
    'Location':'Country'
}, inplace=True)

# QS2024
qs2024.rename(columns={
    'Institution Name':'University_Name'
}, inplace=True)

# CWUR
cwur.rename(columns={
    'institution':'University_Name',
    'country':'Country'
}, inplace=True)

# LIST
list_uni.rename(columns={
    'name':'University_Name',
    'country':'Country'
}, inplace=True)

# QS_FULL
qs2024_full.rename(columns={
    'University':'University_Name',
    'Country_x':'Country'
}, inplace=True)

# QS_HISTORY
qs_history.rename(columns={
    'university':'University_Name',
    'country':'Country'
}, inplace=True)

# THE
the.rename(columns={
    'Name':'University_Name'
}, inplace=True)

# TOP1000
# Already correct

# TOP100
top100.rename(columns={
    'Location':'Country'
}, inplace=True)

In [5]:
for name, df in datasets.items():
    print(f"{name} ->", "University_Name" in df.columns, "Country" in df.columns)

WORLD -> True True
QS2024 -> True True
CWUR -> True True
LIST -> True True
QS_FULL -> True True
QS_HISTORY -> True True
THE -> True True
TOP1000 -> True True
TOP100 -> True True

In [10]:
#Standardize University Names

import re

def clean_university_name(name):
    if pd.isna(name):
        return name

    name = str(name).lower().strip()

    # Remove text inside brackets
    name = re.sub(r'\(.*?\)', '', name)

    # Remove punctuation
    name = re.sub(r'[^\w\s]', '', name)

    # Replace common abbreviations
    name = re.sub(r'\buniv\b', 'university', name)
    name = re.sub(r'\binst\b', 'institute', name)
    name = re.sub(r'\btech\b', 'technology', name)

    # Remove extra spaces
    name = re.sub(r'\s+', ' ', name).strip()

    return name

In [11]:
for df in datasets.values():
    df["University_Name_Clean"] = df["University_Name"].apply(clean_university_name)

In [12]:
for name, df in datasets.items():
    print("\n", name)
    print(df[["University_Name","University_Name_Clean"]].head())

 WORLD
                         University_Name  \
0                     Harvard University
1  Massachusetts Institute of Technology
2                    Stanford University
3                University of Cambridge
4                   University of Oxford

                   University_Name_Clean
0                     harvard university
1  massachusetts institute of technology
2                    stanford university
3                university of cambridge
4                   university of oxford

 QS2024
                                University_Name  \
0                                   institution
1  Massachusetts Institute of Technology (MIT)
2                       University of Cambridge
3                          University of Oxford
4                            Harvard University

                   University_Name_Clean
0                            institution
1  massachusetts institute of technology
2                university of cambridge
3                   university of oxford
4                     harvard university

 CWUR
                         University_Name  \
0                     Harvard University
1  Massachusetts Institute of Technology
2                    Stanford University
3                University of Cambridge
4     California Institute of Technology

                   University_Name_Clean
0                     harvard university
1  massachusetts institute of technology
2                    stanford university
3                university of cambridge
4     california institute of technology

 LIST
                                     University_Name  \
0                            St. George's University
1  Schiller International University, American Co...
2               Business and Hotel Management School
3                     Business School Lausanne (BSL)
4                     Cubidor University Switzerland

                               University_Name_Clean
0                              st georges university
1  schiller international university american col...
2               business and hotel management school
3                           business school lausanne
4                     cubidor university switzerland

 QS_FULL
           University_Name    University_Name_Clean
0  University of Cambridge  university of cambridge
1     University of Oxford     university of oxford
2       Harvard University       harvard university
3      Stanford University      stanford university
4  Imperial College London  imperial college london

 QS_HISTORY
                                University_Name  \
0  Massachusetts Institute of Technology (MIT)
1                           Stanford University
2                            Harvard University
3                       University of Cambridge
4  California Institute of Technology (Caltech)

                   University_Name_Clean
0  massachusetts institute of technology
1                    stanford university
2                     harvard university
3                university of cambridge
4     california institute of technology

 THE
                         University_Name  \
0     California Institute of Technology
1                   University of Oxford
2                    Stanford University
3                University of Cambridge
4  Massachusetts Institute of Technology

                   University_Name_Clean
0     california institute of technology
1                   university of oxford
2                    stanford university
3                university of cambridge
4  massachusetts institute of technology

 TOP1000
                               University_Name  \
0  Massachusetts Institute of Technology (MIT)
1                         University of Oxford
2                          Stanford University
3                           Harvard University
4                      University of Cambridge

                   University_Name_Clean
0  massachusetts institute of technology
1                   university of oxford
2                    stanford university
3                     harvard university
4                university of cambridge

 TOP100
           University_Name    University_Name_Clean
0     University of Oxford     university of oxford
1      Columbia University      columbia university
2   University of Michigan   university of michigan
3  University of Edinburgh  university of edinburgh
4  University of Cambridge  university of cambridge

In [13]:
qs2024.head()

,2024 RANK,2023 RANK,University_Name,Country Code,Country,SIZE,FOCUS,RES.,AGE,STATUS,...,International Students Score,International Students Rank,International Research Network Score,International Research Network Rank,Employment Outcomes Score,Employment Outcomes Rank,Sustainability Score,Sustainability Rank,Overall SCORE,University_Name_Clean
0,rank display,rank display2,institution,location code,location,size,focus,research,age band,status,...,isr score,isr rank,irn score,irn rank,ger score,ger rank,SUS SCORE,SUS RANK,Overall Score,institution
1,1,1,Massachusetts Institute of Technology (MIT),US,United States,M,CO,VH,5,B,...,88.2,128,94.3,58,100,4,95.2,51,100.0,massachusetts institute of technology
2,2,2,University of Cambridge,UK,United Kingdom,L,FC,VH,5,A,...,95.8,85,99.9,7,100,6,97.3,33=,99.2,university of cambridge
3,3,4,University of Oxford,UK,United Kingdom,L,FC,VH,5,A,...,98.2,60,100.0,1,100,3,97.8,26=,98.9,university of oxford
4,4,5,Harvard University,US,United States,L,FC,VH,5,B,...,66.8,223,100.0,5,100,1,96.7,39,98.3,harvard university

In [14]:
# Remove the first row if it is a duplicate header
qs2024 = qs2024[qs2024["University_Name"] != "institution"].reset_index(drop=True)

print(qs2024.shape)
qs2024.head()

(1497, 30)

,2024 RANK,2023 RANK,University_Name,Country Code,Country,SIZE,FOCUS,RES.,AGE,STATUS,...,International Students Score,International Students Rank,International Research Network Score,International Research Network Rank,Employment Outcomes Score,Employment Outcomes Rank,Sustainability Score,Sustainability Rank,Overall SCORE,University_Name_Clean
0,1,1,Massachusetts Institute of Technology (MIT),US,United States,M,CO,VH,5,B,...,88.2,128,94.3,58,100,4,95.2,51,100.0,massachusetts institute of technology
1,2,2,University of Cambridge,UK,United Kingdom,L,FC,VH,5,A,...,95.8,85,99.9,7,100,6,97.3,33=,99.2,university of cambridge
2,3,4,University of Oxford,UK,United Kingdom,L,FC,VH,5,A,...,98.2,60,100.0,1,100,3,97.8,26=,98.9,university of oxford
3,4,5,Harvard University,US,United States,L,FC,VH,5,B,...,66.8,223,100.0,5,100,1,96.7,39,98.3,harvard university
4,5,3,Stanford University,US,United States,L,FC,VH,5,B,...,51.2,284,95.8,44,100,2,94.4,63,98.1,stanford university