In [8]:

import pandas as pd
from pathlib import Path

# Project Paths
PROJECT_ROOT = Path.cwd().parent

RAW_DATA = PROJECT_ROOT / "data" / "raw"
PROCESSED_DATA = PROJECT_ROOT / "data" / "processed"

# Load Dataset
qs = pd.read_csv(RAW_DATA / "qs_rankings_raw.csv")

# Preview
qs.head()

,2024 RANK,2023 RANK,Institution Name,Country Code,Country,SIZE,FOCUS,RES.,AGE,STATUS,...,International Faculty Rank,International Students Score,International Students Rank,International Research Network Score,International Research Network Rank,Employment Outcomes Score,Employment Outcomes Rank,Sustainability Score,Sustainability Rank,Overall SCORE
0,rank display,rank display2,institution,location code,location,size,focus,research,age band,status,...,ifr rank,isr score,isr rank,irn score,irn rank,ger score,ger rank,SUS SCORE,SUS RANK,Overall Score
1,1,1,Massachusetts Institute of Technology (MIT),US,United States,M,CO,VH,5,B,...,56,88.2,128,94.3,58,100,4,95.2,51,100.0
2,2,2,University of Cambridge,UK,United Kingdom,L,FC,VH,5,A,...,64,95.8,85,99.9,7,100,6,97.3,33=,99.2
3,3,4,University of Oxford,UK,United Kingdom,L,FC,VH,5,A,...,110,98.2,60,100.0,1,100,3,97.8,26=,98.9
4,4,5,Harvard University,US,United States,L,FC,VH,5,B,...,210,66.8,223,100.0,5,100,1,96.7,39,98.3

In [9]:
print("Shape :", qs.shape)
print()

print("Columns")
print("-"*50)

for col in qs.columns:
    print(col)

Shape : (1498, 29)

Columns
--------------------------------------------------
2024 RANK
2023 RANK
Institution Name
Country Code
Country
SIZE
FOCUS
RES.
AGE
STATUS
Academic Reputation Score
Academic Reputation Rank
Employer Reputation Score
Employer Reputation Rank
Faculty Student Score
Faculty Student Rank
Citations per Faculty Score
Citations per Faculty Rank
International Faculty Score
International Faculty Rank
International Students Score
International Students Rank
International Research Network Score
International Research Network Rank
Employment Outcomes Score
Employment Outcomes Rank
Sustainability Score
Sustainability Rank
Overall SCORE

In [17]:
print(qs.columns.tolist())

['2024 RANK', '2023 RANK', 'Institution Name', 'Country Code', 'Country', 'SIZE', 'FOCUS', 'RES.', 'AGE', 'STATUS', 'Academic Reputation Score', 'Academic Reputation Rank', 'Employer Reputation Score', 'Employer Reputation Rank', 'Faculty Student Score', 'Faculty Student Rank', 'Citations per Faculty Score', 'Citations per Faculty Rank', 'International Faculty Score', 'International Faculty Rank', 'International Students Score', 'International Students Rank', 'International Research Network Score', 'International Research Network Rank', 'Employment Outcomes Score', 'Employment Outcomes Rank', 'Sustainability Score', 'Sustainability Rank', 'Overall SCORE']

In [22]:
selected_columns = [

    "Institution Name",
    "Country",
    "Country Code",

    "2024 RANK",
    "Overall SCORE",

    "Academic Reputation Score",
    "Employer Reputation Score",

    "Faculty Student Score",

    "Citations per Faculty Score",

    "International Faculty Score",

    "International Students Score",

    "International Research Network Score",

    "Employment Outcomes Score",

    "Sustainability Score"

]

In [23]:
qs_selected = qs[selected_columns]

qs_selected.head()

,Institution Name,Country,Country Code,2024 RANK,Overall SCORE,Academic Reputation Score,Employer Reputation Score,Faculty Student Score,Citations per Faculty Score,International Faculty Score,International Students Score,International Research Network Score,Employment Outcomes Score,Sustainability Score
0,institution,location,location code,rank display,Overall Score,ar score,er score,fsr score,cpf score,ifr score,isr score,irn score,ger score,SUS SCORE
1,Massachusetts Institute of Technology (MIT),United States,US,1,100.0,100.0,100.0,100.0,100.0,100.0,88.2,94.3,100,95.2
2,University of Cambridge,United Kingdom,UK,2,99.2,100.0,100.0,100.0,92.3,100.0,95.8,99.9,100,97.3
3,University of Oxford,United Kingdom,UK,3,98.9,100.0,100.0,100.0,90.6,98.2,98.2,100.0,100,97.8
4,Harvard University,United States,US,4,98.3,100.0,100.0,98.3,100.0,84.6,66.8,100.0,100,96.7

In [24]:
print(qs_selected.shape)

(1498, 14)

In [25]:
qs_selected.to_csv(
    INTERIM_DATA / "qs_selected.csv",
    index=False
)

print("QS selected dataset saved successfully.")

QS selected dataset saved successfully.