In [1]:
from pathlib import Path

print(Path.cwd())

c:\Users\ASUS\Desktop\higher-education-dv\notebooks

In [2]:
import pandas as pd

pd.set_option("display.max_rows", 100)
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)

In [3]:
registry = pd.read_csv("../data/interim/registry/university_registry.csv")

print("Shape :", registry.shape)

registry.head()

Shape : (3565, 4)

,university_id,normalized_name,university_name,country
0,U000001,aalborg university,Aalborg University,Denmark
1,U000002,aalto university,Aalto University,Finland
2,U000003,aarhus university,Aarhus University,Denmark
3,U000004,abai kazakh national pedagogical university,Abai Kazakh National Pedagogical University,Kazakhstan
4,U000005,abbes laghrour university of khenchala,Abbes Laghrour University of Khenchala,Algeria

In [4]:
print(registry.columns.tolist())

['university_id', 'normalized_name', 'university_name', 'country']

In [6]:
print("Duplicate normalized names :")

print(
    registry["normalized_name"]
    .duplicated()
    .sum()
)

Duplicate normalized names :
0

In [7]:
duplicates = registry[
    registry["normalized_name"].duplicated(keep=False)
].sort_values("normalized_name")

duplicates

Empty DataFrame
Columns: [university_id, normalized_name, university_name, country]
Index: []

In [8]:
print("Unique university names :")

print(
    registry["university_name"]
    .nunique()
)

print()

print("Unique normalized names :")

print(
    registry["normalized_name"]
    .nunique()
)

Unique university names :
3565

Unique normalized names :
3565

In [9]:
registry["word_count"] = (
    registry["university_name"]
    .str.split()
    .str.len()
)

registry.sort_values(
    "word_count",
    ascending=False
)[
    [
        "university_name",
        "normalized_name",
        "country",
        "word_count",
    ]
].head(50)

,university_name,normalized_name,country,word_count
564,École Nationale Supérieure des Sciences de la Mer et de l’Aménagement du Littoral (ENSSMAL),ecole nationale superieure des sciences de la mer et de lamenagement du littoral,Algeria,14
723,"George Emil Palade University of Medicine, Pharmacy, Science, and Technology of Targu Mures",george emil palade university of medicine pharmacy science and technology of targu mures,Romania,13
368,Centro de Estudios para la Calidad Educativa y la Investigación Científica (CECEIC),centro de estudios para la calidad educativa y la investigacion cientifica,Mexico,12
583,École Supérieure en Sciences et Technologies de l’Informatique et du Numérique (ESTIN),ecole superieure en sciences et technologies de linformatique et du numerique,Algeria,12
521,Donetsk National University of Economics and Trade named after Mykhailo Tuhan-Baranovsky (DonNUET),donetsk national university of economics and trade named after mykhailo tuhan baranovsky,Ukraine,12
2374,Universidad de las Fuerzas Armadas ESPE (Ex - Escuela Politécnica del Ejército),universidad de las fuerzas armadas espe,Ecuador,12
927,Institute of International Relations of the Ministry of Foreign Affairs of Turkmenistan,institute of international relations of the ministry of foreign affairs of turkmenistan,Turkmenistan,12
2455,Universidad Nacional del Centro de la Provincia de Buenos Aires (UNICEN),universidad nacional del centro de la provincia de buenos aires,Argentina,11
813,"Higher National School of Renewable Energies, Environment and Sustainable Development",higher national school of renewable energies environment and sustainable development,Algeria,10
2657,Université Mohamed El Bachir El Ibrahimi de Bordj Bou Arréridj,universite mohamed el bachir el ibrahimi de bordj bou arreridj,Algeria,10
2509,Universidade Federal de Ciências da Saúde de Porto Alegre (UFCSPA),universidade federal de ciencias da saude de porto alegre,Brazil,10
871,Imam Abdulrahman Bin Faisal University (IAU) (formerly UNIVERSITY OF DAMMAM),imam abdulrahman bin faisal university,Saudi Arabia,10
1086,Kazakh Ablai Khan University of International Relations and World Languages,kazakh ablai khan university of international relations and world languages,Kazakhstan,10
1795,"Royal Central School of Speech and Drama, University of London",royal central school of speech and drama university of london,United Kingdom,10
219,"Balochistan University of Information Technology, Engineering and Management Sciences (BUITEMS)",balochistan university of information technology engineering and management sciences,Pakistan,10
369,Centro Federal de Educação Tecnológica Celso Suckow da Fonseca (CEFET-RJ),centro federal de educacao tecnologica celso suckow da fonseca,Brazil,10
662,Federal University of the State of Rio de Janeiro (UNIRIO),federal university of the state of rio de janeiro,Brazil,10
204,B. S. Abdur Rahman Crescent Institute of Science and Technology,b s abdur rahman crescent institute of science and technology,India,10
1377,Moscow Institute of Physics and Technology (MIPT / Moscow Phystech),moscow institute of physics and technology,Russia,10
2288,"ULACIT - Universidad Latinoamericana de Ciencia y Tecnología, Costa Rica",ulacit universidad latinoamericana de ciencia y tecnologia costa rica,Costa Rica,10
2526,Universidade Federal do Estado do Rio de Janeiro - UNIRIO,universidade federal do estado do rio de janeiro unirio,Brazil,10
1473,"National Technical University of Ukraine ""Igor Sikorsky Kyiv Polytechnic Institute""",national technical university of ukraine igor sikorsky kyiv polytechnic institute,Ukraine,10
2606,Universitatea de Vest din Timisoara / West University of Timisoara,universitatea de vest din timisoara west university of timisoara,Romania,10
100,Alisher Navo’i Tashkent State University of Uzbek Language and Literature,alisher navoi tashkent state university of uzbek language and literature,Uzbekistan,10
1869,Sathyabama Institute of Science and Technology (deemed to be university),sathyabama institute of science and technology,India,10
2479,"Universidad Tecnológica de la Habana José Antonio Echeverría, Cujae",universidad tecnologica de la habana jose antonio echeverria cujae,Cuba,9
1489,National University of Life and Environmental Sciences of Ukraine,national university of life and environmental sciences of ukraine,Ukraine,9
3221,University of Science and Technology of Southern Philippines (USTP),university of science and technology of southern philippines,Philippines,9
1447,National Institute of Applied Sciences of Lyon (INSA Lyon),national institute of applied sciences of lyon,France,9
1470,National Taiwan University of Science and Technology (Taiwan Tech),national taiwan university of science and technology,Taiwan,9
892,Indian Institute of Technology (Indian School of Mines) Dhanbad,indian institute of technology dhanbad,India,9
1708,Pontificia Universidade Católica do Minas Gerais - PUC Minas,pontificia universidade catolica do minas gerais puc minas,Brazil,9
2167,The London School of Economics and Political Science (LSE),the london school of economics and political science,United Kingdom,9
987,IUBAT – International University of Business Agriculture and Technology,iubat international university of business agriculture and technology,Bangladesh,9
2750,University of Applied Sciences and Arts of Western Switzerland,university of applied sciences and arts of western switzerland,Switzerland,9
2729,University of Agronomic Sciences and Veterinary Medicine of Bucharest,university of agronomic sciences and veterinary medicine of bucharest,Romania,9
573,École Normale Supérieure El Katiba Assia Djebar Constantine (ENSC),ecole normale superieure el katiba assia djebar constantine,Algeria,9
2824,University of Canterbury | Te Whare Wānanga o Waitaha,university of canterbury te whare wananga o waitaha,New Zealand,9
220,"Bamidele Olumilua University of Education, Science and Technology, Ikere-Ikiti",bamidele olumilua university of education science and technology ikere ikiti,Nigeria,9
676,Financial University under the Government of the Russian Federation,financial university under the government of the russian federation,Russia,9
579,École Supérieure de Comptabilité et de Finances de Constantine,ecole superieure de comptabilite et de finances de constantine,Algeria,9
991,Ivano Frankivsk National Technical University of Oil and Gas,ivano frankivsk national technical university of oil and gas,Ukraine,9
1809,Russian Presidential Academy of National Economy and Public Administration,russian presidential academy of national economy and public administration,Russia,9
1457,National Research Nuclear University MEPhI (Moscow Engineering Physics Institute),national research nuclear university mephi,Russia,9
1054,KAIST - Korea Advanced Institute of Science & Technology,kaist korea advanced institute of science and technology,South Korea,9
1645,Paris Sciences et Lettres – PSL Research University Paris,paris sciences et lettres psl research university paris,France,9
1810,Russian State Agrarian University - Moscow Timiryazev Agricultural Academy,russian state agrarian university moscow timiryazev agricultural academy,Russia,9
580,École Supérieure en Informatique 8 Mai 1945 de Sidi-Bel-Abbès,ecole superieure en informatique 8 mai 1945 de sidi bel abbes,Algeria,9
926,"Institute of Engineering, Technical and Transport Communications of Turkmenistan",institute of engineering technical and transport communications of turkmenistan,Turkmenistan,9
1696,Pontifical Catholic University of Rio Grande do Sul (PUCRS),pontifical catholic university of rio grande do sul,Brazil,9

In [10]:
registry[
    registry["university_name"]
    .str.contains(
        "MIT|IIT|NUS|UC|University of California|Oxford|Cambridge",
        case=False,
        na=False,
        regex=True,
    )
][
    [
        "university_name",
        "normalized_name",
        "country",
    ]
]

,university_name,normalized_name,country
123,Amity University,amity university,India
124,"Amity University, Chhattisgarh",amity university chhattisgarh,India
125,"Amity University, Gurugram",amity university gurugram,India
126,"Amity University, Gwalior",amity university gwalior,India
127,"Amity University, Mumbai",amity university mumbai,India
...,...,...,...
3395,University POLITEHNICA of Bucharest,university politehnica of bucharest,Romania
3464,Vytautas Magnus University,vytautas magnus university,Lithuania
3486,Western Kentucky University,western kentucky university,United States
3518,Yamaguchi Prefectural University,yamaguchi prefectural university,Japan
3519,Yamaguchi University,yamaguchi university,Japan