In [1]:
import pandas as pd

pd.set_option("display.max_rows", 100)
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)

In [2]:
unmatched = pd.read_csv("../data/processed/openalex_unmatched.csv")

print("Rows :", len(unmatched))

unmatched.head()

Rows : 1118

,university_id,normalized_name,university_name,country
0,U000005,abbes laghrour university of khenchala,Abbes Laghrour University of Khenchala,Algeria
1,U000007,abdelhafid boussouf university center of mila,Abdelhafid Boussouf University Center of Mila,Algeria
2,U000014,abo akademi university,Abo Akademi University,Finland
3,U000017,academician y a buketov karaganda university,Academician Y.A. Buketov Karaganda University,Kazakhstan
4,U000021,ada kent university,Ada Kent University,Northern Cyprus

In [3]:
print(unmatched.columns.tolist())

['university_id', 'normalized_name', 'university_name', 'country']

In [4]:
print("Top Countries")

unmatched["country"].value_counts().head(30)

Top Countries

country
France                66
Brazil                61
United States         60
Algeria               58
Spain                 57
Germany               53
Turkey                46
India                 37
Italy                 33
Colombia              33
United Kingdom        31
Pakistan              31
Kazakhstan            28
Uzbekistan            26
Iraq                  26
Mexico                25
Chile                 24
Indonesia             24
Nigeria               24
Russia                22
Russian Federation    21
Argentina             21
Poland                19
Ukraine               14
Malaysia              14
Japan                 13
Romania               13
Ecuador               12
Portugal              11
Morocco                9
Name: count, dtype: int64

In [5]:
unmatched["university_name"].sample(100, random_state=42)

996                                                                       University of Missouri, Columbia
101                                                                                     Cankaya University
486                                                   Panteion University of Social and Political Sciences
711                                                                                        Umea University
777                                                                  Universidad Nacional de Córdoba - UNC
793                                                                     Universidad Tecnológica de Pereira
525                                                                                      Purdue University
696                                                                Toyota Technological Institute in Japan
128                                                                          China University of Petroleum
958                                                                                     University of Hail
621                                                                     Teacher Education College of Setif
88                                                                                      Blida 1 University
1037                                                           University of South Santa Catarina (Unisul)
479                                                                                       Osaka University
453                                                                         Nigerian Police Academy, Wudil
772                                                              Universidad Industrial de Santander (UIS)
485                                                                            Pablo de Olavide University
44                                                                                         Anna University
846                                                                           Université 8 Mai 1945 Guelma
277                                                                              Hyogo College of Medicine
109                                                                                    Católica de Córdoba
113                                                                                        Centrale Nantes
209                                                                   Federal University of Espírito Santo
56                                                                                      Ataturk University
666                                                                                 The University of Aizu
328                                                                        Johannes Kepler University Linz
497                                                 Pavlov First Saint Petersburg State Medical University
674                                                                               The University of Exeter
318                                                                    Jabir ibn Hayyan Medical University
156     Donetsk National University of Economics and Trade named after Mykhailo Tuhan-Baranovsky (DonNUET)
1107                                                            Westfälische Wilhelms-Universität Münster
1023                                                                                University of Rome III
767                                                                                  Universidad del Cauca
424                                                      Nanyang Technological University, Singapore (NTU)
843                                                                                     Universität Siegen
86                                                                              Binghamton University SUNY
813                                                                    Università Vita-Salute San Raffaele
844                                                                                  Universität Stuttgart
900                                                                     University Center Ali Kafi Tindouf
554                                                   S.D. Asfendiyarov Kazakh National Medical University
243                                                               Florida Atlantic University - Boca Raton
740                                                                      Universidad de Castilla-La Mancha
1111                                                                                           WSB Academy
477                                                                                 ORT Uruguay University
1065                                                                         University of Urbino Carlo Bo
535                                                                              Rennes School of Business
885                                                                                 Universiti Malaya (UM)
781                                                                        Universidad Nacional de Quilmes
96                                                                         Bukhara State Medical Institute
629                                                           Technische Universität Bergakademie Freiberg
334                                                                   Karaganda State Technical University
529                                                                                    Radboud University
319                                                                               Jamia Hamdard University
907                                                                              University of Ahmed Draia
51                                                         Asfendiyarov Kazakh National Medical University
833                                                                             Universität Duisburg-Essen
1113                                           Yagshigeldi Kakayev International University of Oil and Gas
70                                                                                 Babes-Bolyai University
344                                                                     Kazakhstan Medical University KSPH
1106                                                                                      Wasit University
220                                                                          Federal University of Pelotas
714                                                            UNIR – International University of La Rioja
743                                                                      Universidad de Córdoba - Colombia
894                                               Universiti Tun Hussein Onn University of Malaysia (UTHM)
985                                                                                  University of Marburg
323                                                                        Jean Moulin University – Lyon 3
321                                                                   Jan Kochanowski University in Kielce
877                                                                   Université Paris-Sorbonne (Paris IV)
467                                                                                       Óbuda University
1048                                                                            University of Texas Dallas
812                                                                   Universita' Politecnica delle Marche
808                                                                        Università degli studi Roma Tre
231                                                           Federal University of Toulouse Midi-Pyrénées
286                                                          Indian Institute of Technology (BHU) Varanasi
31                                                            Alma Mater Studiorum - University of Bologna
582                                           Shoolini University of Biotechnology and Management Sciences
801                                                               Universidade Federal Rural do Semi-Arido
790                                                                      UNIVERSIDAD POLITECNICA SALESIANA
210                                                                            Federal University of Goiás
939                                                                                   University of Deusto
198                                                                                  ESSEC Business School
433                                                         National Research Tomsk Polytechnic University
1035                                                                           University of South Bohemia
291                                                     Institut Teknologi Sepuluh Nopember (ITS Surabaya)
987                                                                                  University of Mascara
199                                                                                   Essex, University of
761                                                          Universidad de San Carlos de Guatemala - USAC
138                                                                Colorado State University, Fort Collins
363                                                                                Kore University of Enna
331                                                                       Justus-Liebig-University Giessen
715                                                                                    Unisinos University
875                                                               Université Mouloud Mammeri de Tizi-Ouzou
979                                                                                     University of Lodz
10                                                                                Aix-Marseille University
352                                               King Abdullah University of Science & Technology (KAUST)
290                                  Institut polytechnique de Grenoble - Grenoble Institute of Technology
359                                                               Kocaeli Health and Technology University
937                                                                              University of Côte d’Azur
731                                                                         Universidad Católica del Maule
1012                                                                                  University of Oviedo
Name: university_name, dtype: object

In [6]:
keywords = [
    "technology",
    "institute",
    "college",
    "science",
    "medical",
    "engineering",
    "business",
    "management",
    "polytechnic",
    "university",
]

for word in keywords:

    count = unmatched["university_name"].str.contains(
        word,
        case=False,
        na=False,
    ).sum()

    print(f"{word:<15} {count}")

technology      54
institute       49
college         29
science         60
medical         32
engineering     13
business        9
management      6
polytechnic     10
university      740

In [7]:
unmatched[
    unmatched["university_name"]
    .str.contains(
        r"\(",
        regex=True,
        na=False,
    )
][
    [
        "university_name",
        "country",
    ]
]

,university_name,country
39,Andijan State Pedagogical Institute (ASPI),Uzbekistan
40,Andrés Bello Catholic University (UCAB),Venezuela
49,Arkin University of Creative Arts and Design (ARUCAD),Northern Cyprus
54,Asia Pacific University of Technology and Innovation (APU),Malaysia
61,Auezov South Kazakhstan University (SKU),Kazakhstan
85,Bina Nusantara University (BINUS),Indonesia
99,Canadian International College (CIC) – Cairo,Egypt
115,Centro de Estudios para la Calidad Educativa y la Investigación Científica (CECEIC),Mexico
116,Centro Federal de Educação Tecnológica Celso Suckow da Fonseca (CEFET-RJ),Brazil
156,Donetsk National University of Economics and Trade named after Mykhailo Tuhan-Baranovsky (DonNUET),Ukraine
172,École Nationale Supérieure de Biotechnologie Taoufik Khaznadar (ENSB),Algeria
174,École Nationale Supérieure des Sciences de la Mer et de l’Aménagement du Littoral (ENSSMAL),Algeria
180,École Normale Supérieure El Katiba Assia Djebar Constantine (ENSC),Algeria
185,École Supérieure en Sciences Biologiques d’Oran (ESSBO),Algeria
186,École Supérieure en Sciences et Technologies de l’Informatique et du Numérique (ESTIN),Algeria
195,Escuela Superior Politécnica del Litoral (ESPOL),Ecuador
214,Federal University of Latin American Integration (UNILA),Brazil
219,Federal University of Paraí­ba (UFPB),Brazil
225,Federal University of Rio Grande do Norte (UFRN),Brazil
229,Federal University of the State of Rio de Janeiro (UNIRIO),Brazil
254,Gebze Yüksek Teknoloji Enstitüsü (GYTE),Turkey
266,Higher School of Agronomy – Mostaganem (ESAM),Algeria
267,Higher School of Management and Digital Economy (HSMDE),Algeria
273,HUFS - Hankuk (Korea) University of Foreign Studies,South Korea
283,Imam Al-Kadhum College (IKC),Iraq
286,Indian Institute of Technology (BHU) Varanasi,India
291,Institut Teknologi Sepuluh Nopember (ITS Surabaya),Indonesia
300,International Engineering and Technology University (METU),Kazakhstan
306,"Islamic Azad University, Najafabad Branch (IAUN)",Iran
352,King Abdullah University of Science & Technology (KAUST),Saudi Arabia
373,Liaquat University of Medical and Health Sciences (LUMHS),Pakistan
380,London Academy of Music and Dramatic Art (LAMDA),United Kingdom
388,Maharishi Markandeshwar University (MMU),India
394,Marian College Kuttikkanam (Autonomous),India
419,Moscow State University of Technology (STANKIN),Russian Federation
424,"Nanyang Technological University, Singapore (NTU)",Singapore
430,National Institute of Applied Sciences of Lyon (INSA Lyon),France
434,National Research University Moscow Power Engineering Institute (MPEI),Russia
440,National University of Distance Education (UNED),Spain
442,"National University of Modern Languages (NUML), Islamabad",Pakistan
445,National University of Sciences And Technology (NUST) Islamabad,Pakistan
454,Nitte (Deemed to be University),India
460,Northern (Arctic) Federal University named after M.V. Lomonosov,Russian Federation
468,October University for Modern Sciences and Arts (MSA),Egypt
471,Ohio State University (Main campus),United States
487,Panthéon-Assas University (Paris 2),France
499,Penn State (Main campus),United States
514,Pontifical Catholic University of Rio de Janeiro (PUC-Rio),Brazil
515,Pontifical Catholic University of Rio Grande do Sul (PUCRS),Brazil
530,Rajamangala University of Technology Thanyaburi (RMUTT),Thailand
545,Russian Biotechnological University (BIOTECH),Russian Federation
547,Russian University of State for Social (RUSS),Russian Federation
558,Saint Joseph University of Beirut (USJ),Lebanon
572,School of Higher Commercial Studies (EHEC Algiers),Algeria
585,Siksha 'O' Anusandhan (Deemed to be University),India
593,SRUC (Scotland’s Rural College),United Kingdom
597,St Petersburg Electrotechnical University (LETI),Russian Federation
645,The Chinese University of Hong Kong (CUHK),Hong Kong SAR
660,The London School of Economics and Political Science (LSE),United Kingdom
680,The University of New South Wales (UNSW Sydney),Australia
681,"The University of Newcastle, Australia (UON)",Australia
689,The World Islamic Sciences and Education University (WISE),Jordan
724,Universidad Autónoma de Querétaro (UAQ),Mexico
732,Universidad Católica San Antonio de Murcia (UCAM),Spain
747,Universidad de la República (Udelar),Uruguay
750,Universidad de Las Américas (UDLA) Ecuador,Ecuador
751,Universidad de Los Andes - (ULA) Mérida,Venezuela
752,Universidad de Monterrey (UDEM),Mexico
754,Universidad de Palermo (UP),Argentina
765,Universidad de Valparaíso (UV),Chile
769,Universidad del Valle de Mexico (UVM),Mexico
772,Universidad Industrial de Santander (UIS),Colombia
775,Universidad Nacional Autónoma de Honduras (UNAH),Honduras
783,Universidad Nacional de Rosario (UNR),Argentina
791,Universidad Tecnica Particular De Loja (UTPL),Ecuador
794,Universidad Tecnológica Nacional (UTN),Argentina
839,Universitat Politècnica de Catalunya · BarcelonaTech (UPC),Spain
847,Université catholique de Louvain (UCLouvain),Belgium
877,Université Paris-Sorbonne (Paris IV),France
883,Universiti Kebangsaan Malaysia (UKM),Malaysia
884,Universiti Kuala Lumpur (UniKL),Malaysia
885,Universiti Malaya (UM),Malaysia
887,Universiti Malaysia Sabah (UMS),Malaysia
888,Universiti Pendidikan Sultan Idris (UPSI),Malaysia
893,Universiti Tun Hussein Onn Malaysia (UTHM),Malaysia
894,Universiti Tun Hussein Onn University of Malaysia (UTHM),Malaysia
895,Universiti Utara Malaysia (UUM),Malaysia
926,University of Camerino (Unicam),Italy
944,University of Engineering & Technology (UET) Lahore,Pakistan
948,University of Fortaleza (UNIFOR),Brazil
963,University of Illinois at Chicago (UIC),United States
973,University of Las Américas (UDLA),Ecuador
1013,University of Passo Fundo (UPF),Brazil
1028,"University of Santiago, Chile (USACH)",Chile
1037,University of South Santa Catarina (Unisul),Brazil
1039,University of Sufism and Modern Sciences (USMS),Pakistan
1094,Vellore Institute of Technology (VIT),India
1098,Viet Nam National University Ho Chi Minh City (VNU-HCM),Vietnam
1105,Warsaw University of Life Sciences – SGGW (WULS-SGGW),Poland
1110,Wroclaw University of Science and Technology (WRUST),Poland

In [8]:
unmatched[
    unmatched["university_name"]
    .str.len() < 30
][
    [
        "university_name",
        "country",
    ]
].head(100)

                   university_name               country
2           Abo Akademi University               Finland
4              Ada Kent University       Northern Cyprus
7          AECC University College        United Kingdom
8      African School of Economics                 Benin
10        Aix-Marseille University                France
11            Akdeniz Üniversitesi                Turkey
12                 AKFA University            Uzbekistan
13       Akhmet Yassawi University            Kazakhstan
15   Al Akhawayn University Ifrane               Morocco
16              Al-Ayen University                  Iraq
17     Al-Esraa University College                  Iraq
21             Al-Kitab University                  Iraq
22    Al-Maarif University College                  Iraq
25           Al-Nahrain University                  Iraq
26     Al-Qalam University College                  Iraq
29     Al Safwa University College                  Iraq
35       Amity University, Gwalior                 India
37              Anáhuac University                Mexico
41       Ankara Science University                Turkey
42             Ankara Üniversitesi                Turkey
44                 Anna University                 India
45       Antonio Nariño University              Colombia
47   Arab Open University – Kuwait                Kuwait
48    Arab Open University Lebanon               Lebanon
52                Ashur University                  Iraq
53        Ashur University College                  Iraq
55          Asia University Taiwan                Taiwan
56              Ataturk University                Turkey
57               Atılım University                Turkey
59               Atyrau University            Kazakhstan
60                        Audencia                France
62            Augustine University               Nigeria
70         Babes-Bolyai University               Romania
78               Bayero University               Nigeria
80   Bernardo O’Higgins University                 Chile
81      Bezmiâlem Vakif University                Turkey
83   Bharati Vidyapeeth University                 India
86      Binghamton University SUNY         United States
87    Birmingham Newman University        United Kingdom
88              Blida 1 University               Algeria
89           Bogaziçi Üniversitesi                Turkey
90   Bogor Agricultural University             Indonesia
93                Bozok University                Turkey
94        Brunel University London        United Kingdom
97         Bursa Uludağ University                Turkey
100      Canadian University Dubai  United Arab Emirates
101             Cankaya University                Turkey
104             Catania University                 Italy
109            Católica de Córdoba             Argentina
111         Ceará State University                Brazil
113                Centrale Nantes                France
114                CentraleSupélec                France
117    Centro Universitário Cesuca                Brazil
120                 CES University              Colombia
122               CEU Universities                 Spain
124   Charles University in Prague        Czech Republic
128  China University of Petroleum      China (Mainland)
133         Civil Aviation Academy            Kazakhstan
135           Coal City University               Nigeria
136              Colegio de México                Mexico
137    College of William and Mary         United States
144      CY Cergy Paris University                France
149         Del Rosario University              Colombia
152      Diego Portales University                 Chile
153              Dijlah University                  Iraq
154       Dokuz Eylül Üniversitesi                Turkey
155           Don Bosco University                 India
159          Dumlupinar University                Turkey
160               Duzce University                Turkey
161               EAFIT University              Colombia
162                 EAN University              Colombia
164            EBS Business School               Germany
167      Ecole des Ponts ParisTech                France
169  École Nationale Polytechnique               Algeria
182            Ecole Polytechnique                France
187           El Bosque University              Colombia
188               ENS Paris-Saclay                France
189                 ENSTA Bretagne                France
190                           EPFL           Switzerland
191           Erciyes Üniversitesi                Turkey
192   ESCP Business School - Paris                France
193   Escuela Politécnica Nacional               Ecuador
196                           ESIC                 Spain
198          ESSEC Business School                France
199           Essex, University of        United Kingdom
201  European University of Madrid                 Spain
202   European University of Tunis               Tunisia
204     Evangel University, Akaeze               Nigeria
208  Federal University of Alagoas                Brazil
210    Federal University of Goiás                Brazil
211  Federal University of Itajubá                Brazil
212  Federal University of Kashere               Nigeria
213    Federal University of Lafia               Nigeria
215   Federal University of Lavras                Brazil
218     Federal University of Pará                Brazil
220  Federal University of Pelotas                Brazil
223    Federal University of Piauí                Brazil
234   Federal University of Viçosa                Brazil
237  Fergana Polytechnic Institute            Uzbekistan
238       Fergana State University            Uzbekistan