In [1]:
import pandas as pd
import numpy as np

In [2]:
path = r"C:\Users\yadav\higher-education-dv\datasets\processed_data\university_cleaned.csv"

df = pd.read_csv(path)

print(df.shape)
df.head()

(668, 89)

,university_id,world_rank,2023 RANK,university_name,country_code_iso,country,SIZE,FOCUS,RES.,AGE,...,THE_Rank,ARWU_Rank,Education Rank,Employability Rank,Faculty Rank,Research Rank,web_pages,country_code,h_index,degree_level
0,1,2,2,University of Cambridge,UK,United Kingdom,L,FC,VH,5,...,5,4,3.0,25,4.0,10,http://www.cam.ac.uk/,GB,254.0,Undergraduate & Postgraduate
1,2,3,4,University of Oxford,UK,United Kingdom,L,FC,VH,5,...,1,6,7.0,27,9.0,4,http://www.ox.ac.uk/,GB,320.0,Undergraduate & Postgraduate
2,3,4,5,Harvard University,US,United States,L,FC,VH,5,...,3,1,1.0,1,1.0,1,http://www.harvard.edu/,US,343.0,Undergraduate & Postgraduate
3,4,5,3,Stanford University,US,United States,L,FC,VH,5,...,6,2,11.0,4,3.0,2,http://www.stanford.edu/,US,230.0,Undergraduate & Postgraduate
4,5,6,6=,Imperial College London,UK,United Kingdom,L,FC,VH,5,...,9,23,69.0,117,53.0,17,http://www.imperial.ac.uk/,GB,243.0,Undergraduate & Postgraduate

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 668 entries, 0 to 667
Data columns (total 89 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   university_id                         668 non-null    int64
 1   world_rank                            668 non-null    object
 2   2023 RANK                             668 non-null    object
 3   university_name                       668 non-null    object
 4   country_code_iso                      668 non-null    object
 5   country                               668 non-null    object
 6   SIZE                                  668 non-null    object
 7   FOCUS                                 668 non-null    object
 8   RES.                                  668 non-null    object
 9   AGE                                   668 non-null    int64
 10  STATUS                                668 non-null    object
 11  academic_reputation_score             668 non-null    float64
 12  Academic Reputation Rank              668 non-null    object
 13  employer_reputation_score             668 non-null    float64
 14  Employer Reputation Rank              668 non-null    object
 15  Faculty Student Score                 668 non-null    float64
 16  Faculty Student Rank                  668 non-null    object
 17  citations_per_faculty                 668 non-null    float64
 18  Citations per Faculty Rank            668 non-null    object
 19  International Faculty Score           668 non-null    float64
 20  International Faculty Rank            668 non-null    object
 21  International Students Score          668 non-null    float64
 22  International Students Rank           668 non-null    object
 23  International Research Network Score  668 non-null    float64
 24  International Research Network Rank   668 non-null    object
 25  Employment Outcomes Score             668 non-null    float64
 26  Employment Outcomes Rank              668 non-null    object
 27  Sustainability Score                  668 non-null    float64
 28  Sustainability Rank                   668 non-null    object
 29  overall_score                         668 non-null    float64
 30  student_population                    668 non-null    int64
 31  students_to_staff_ratio               668 non-null    float64
 32  international_students_count          668 non-null    object
 33  gender_ratio                          668 non-null    object
 34  teaching_score                        668 non-null    float64
 35  research_environment_score            668 non-null    float64
 36  research_quality_score                668 non-null    float64
 37  industry_impact_score                 668 non-null    float64
 38  international_outlook_score           668 non-null    float64
 39  Quality of Education                  668 non-null    float64
 40  Alumni Employment                     668 non-null    int64
 41  Quality of Faculty                    668 non-null    int64
 42  Research_Output_x                     668 non-null    int64
 43  publications_count                    668 non-null    int64
 44  Influence                             668 non-null    float64
 45  citations_count                       668 non-null    int64
 46  Score                                 668 non-null    float64
 47  Latitude                              668 non-null    float64
 48  Longitude                             668 non-null    float64
 49  city                                  668 non-null    object
 50  region                                668 non-null    object
 51  university_type                       668 non-null    object
 52  research_output                       668 non-null    object
 53  student_faculty_ratio                 668 non-null    int64
 54  faculty_count                         668 non-null    object
 55  universities_ranked_count             668 non-null    int64
 56  best_university_rank                  668 non-null    int64
 57  country_avg_overall_score             668 non-null    float64
 58  country_avg_academic_reputation       668 non-null    float64
 59  country_avg_rank                      668 non-null    float64
 60  country_avg_citations                 668 non-null    float64
 61  country_avg_international_ratio       668 non-null    float64
 62  research_productivity_index           668 non-null    float64
 63  female_percentage                     668 non-null    float64
 64  male_percentage                       668 non-null    int64
 65  subject_field                         668 non-null    object
 66  citations_score                       668 non-null    float64
 67  research_output_score                 668 non-null    int64
 68  total_students                        668 non-null    int64
 69  undergraduate_students                668 non-null    int64
 70  postgraduate_students                 668 non-null    int64
 71  faculty_to_student_ratio              668 non-null    float64
 72  international_student_ratio           668 non-null    int64
 73  tuition_fee_usd                       668 non-null    int64
 74  acceptance_rate                       668 non-null    int64
 75  graduation_rate                       668 non-null    int64
 76  Employability_Rank                    668 non-null    int64
 77  qs_subject_rank                       668 non-null    int64
 78  QS_Rank                               668 non-null    int64
 79  THE_Rank                              668 non-null    int64
 80  ARWU_Rank                             668 non-null    int64
 81  Education Rank                        668 non-null    float64
 82  Employability Rank                    668 non-null    int64
 83  Faculty Rank                          668 non-null    float64
 84  Research Rank                         668 non-null    int64
 85  web_pages                             668 non-null    object
 86  country_code                          668 non-null    object
 87  h_index                               662 non-null    float64
 88  degree_level                          662 non-null    object
dtypes: float64(33), int64(27), object(29)
memory usage: 464.6+ KB

In [4]:
required_columns = [
    "world_rank",
    "academic_reputation_score",
    "citations_count",
    "Research_Output_x",
    "Student Population",
    "faculty_count",
    "international_students_count"
]

for col in required_columns:
    print(col, "->", col in df.columns)

world_rank -> True
academic_reputation_score -> True
citations_count -> True
Research_Output_x -> True
Student Population -> False
faculty_count -> True
international_students_count -> True

In [5]:
# Global Ranking Score (Higher is Better)
df["global_ranking_score"] = 1000 - pd.to_numeric(df["world_rank"], errors="coerce")

# Research Impact Score
df["research_impact_score"] = (
    df["citations_count"] +
    df["Research_Output_x"] +
    df["research_productivity_index"]
) / 3

# Faculty to Student Ratio
df["faculty_student_ratio_kpi"] = df["faculty_to_student_ratio"]

# International Student Percentage
df["international_student_percentage"] = df["international_student_ratio"]

# Academic Reputation Score
df["academic_reputation_kpi"] = df["academic_reputation_score"]

# Research Productivity Index
df["research_productivity_kpi"] = df["research_productivity_index"]

print(df.shape)

(668, 95)

In [6]:
df[
    [
        "university_name",
        "global_ranking_score",
        "research_impact_score",
        "faculty_student_ratio_kpi",
        "international_student_percentage",
        "academic_reputation_kpi",
        "research_productivity_kpi"
    ]
].head()

,university_name,global_ranking_score,research_impact_score,faculty_student_ratio_kpi,international_student_percentage,academic_reputation_kpi,research_productivity_kpi
0,University of Cambridge,998.0,42.100000,11.5,38,100.0,95.300000
1,University of Oxford,997.0,37.411111,10.8,43,100.0,99.233333
2,Harvard University,996.0,32.166667,10.0,25,100.0,94.500000
3,Stanford University,995.0,37.044444,5.9,23,100.0,99.133333
4,Imperial College London,994.0,48.333333,12.1,60,98.3,95.000000

In [7]:
output_path = r"C:\Users\yadav\higher-education-dv\datasets\processed_data\university_final_dataset.xlsx"

df.to_excel(output_path, index=False)

print("Final Dataset Saved Successfully!")

Final Dataset Saved Successfully!